/**
 * Comprehensive city database for Anatoly Mook SEO pages.
 * Brand: Klarheit, bewusste Führung & persönliche Meisterschaft.
 * 185 cities across DACH region and international markets.
 */

export interface CityData {
  slug: string;
  name: string;
  nameLocal: string;
  country: string;
  countryCode: string;
  region: string;
  coordinates: { lat: number; lng: number };
  population: number;
  wikidataId: string;
  timezone: string;
  languages: string[];
}

export function slugify(name: string): string {
  return name
    .replace(/ä/g, 'ae')
    .replace(/Ä/g, 'Ae')
    .replace(/ö/g, 'oe')
    .replace(/Ö/g, 'Oe')
    .replace(/ü/g, 'ue')
    .replace(/Ü/g, 'Ue')
    .replace(/ß/g, 'ss')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[.\s]+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// ---------------------------------------------------------------------------
// City data — organised by country / region
// ---------------------------------------------------------------------------

export const allCities: CityData[] = [
  // ==========================================================================
  // GERMANY (60 cities)
  // ==========================================================================
  {
    slug: 'berlin',
    name: 'Berlin',
    nameLocal: 'Berlin',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Berlin',
    coordinates: { lat: 52.52, lng: 13.405 },
    population: 3_677_000,
    wikidataId: 'Q64',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'muenchen',
    name: 'München',
    nameLocal: 'München',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bayern',
    coordinates: { lat: 48.1351, lng: 11.582 },
    population: 1_488_000,
    wikidataId: 'Q1726',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'hamburg',
    name: 'Hamburg',
    nameLocal: 'Hamburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Hamburg',
    coordinates: { lat: 53.5511, lng: 9.9937 },
    population: 1_854_000,
    wikidataId: 'Q1055',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'koeln',
    name: 'Köln',
    nameLocal: 'Köln',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 50.9375, lng: 6.9603 },
    population: 1_084_000,
    wikidataId: 'Q365',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'frankfurt',
    name: 'Frankfurt',
    nameLocal: 'Frankfurt am Main',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Hessen',
    coordinates: { lat: 50.1109, lng: 8.6821 },
    population: 764_000,
    wikidataId: 'Q1794',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'stuttgart',
    name: 'Stuttgart',
    nameLocal: 'Stuttgart',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 48.7758, lng: 9.1829 },
    population: 635_000,
    wikidataId: 'Q1022',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'duesseldorf',
    name: 'Düsseldorf',
    nameLocal: 'Düsseldorf',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.2277, lng: 6.7735 },
    population: 621_000,
    wikidataId: 'Q1718',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'dortmund',
    name: 'Dortmund',
    nameLocal: 'Dortmund',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.5136, lng: 7.4653 },
    population: 588_000,
    wikidataId: 'Q1295',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'essen',
    name: 'Essen',
    nameLocal: 'Essen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.4556, lng: 7.0116 },
    population: 582_000,
    wikidataId: 'Q2066',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'leipzig',
    name: 'Leipzig',
    nameLocal: 'Leipzig',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Sachsen',
    coordinates: { lat: 51.3397, lng: 12.3731 },
    population: 610_000,
    wikidataId: 'Q2079',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'bremen',
    name: 'Bremen',
    nameLocal: 'Bremen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bremen',
    coordinates: { lat: 53.0793, lng: 8.8017 },
    population: 567_000,
    wikidataId: 'Q24879',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'dresden',
    name: 'Dresden',
    nameLocal: 'Dresden',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Sachsen',
    coordinates: { lat: 51.0504, lng: 13.7373 },
    population: 561_000,
    wikidataId: 'Q1731',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'hannover',
    name: 'Hannover',
    nameLocal: 'Hannover',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Niedersachsen',
    coordinates: { lat: 52.3759, lng: 9.732 },
    population: 536_000,
    wikidataId: 'Q1715',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'nuernberg',
    name: 'Nürnberg',
    nameLocal: 'Nürnberg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bayern',
    coordinates: { lat: 49.4521, lng: 11.0767 },
    population: 520_000,
    wikidataId: 'Q2090',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'duisburg',
    name: 'Duisburg',
    nameLocal: 'Duisburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.4344, lng: 6.7623 },
    population: 498_000,
    wikidataId: 'Q2100',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'bochum',
    name: 'Bochum',
    nameLocal: 'Bochum',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.4818, lng: 7.2162 },
    population: 365_000,
    wikidataId: 'Q2103',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'wuppertal',
    name: 'Wuppertal',
    nameLocal: 'Wuppertal',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.2562, lng: 7.1508 },
    population: 355_000,
    wikidataId: 'Q2104',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'bielefeld',
    name: 'Bielefeld',
    nameLocal: 'Bielefeld',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 52.0302, lng: 8.5325 },
    population: 334_000,
    wikidataId: 'Q2112',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'bonn',
    name: 'Bonn',
    nameLocal: 'Bonn',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 50.7374, lng: 7.0982 },
    population: 331_000,
    wikidataId: 'Q586',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'muenster',
    name: 'Münster',
    nameLocal: 'Münster',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.9607, lng: 7.6261 },
    population: 317_000,
    wikidataId: 'Q2742',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'karlsruhe',
    name: 'Karlsruhe',
    nameLocal: 'Karlsruhe',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 49.0069, lng: 8.4037 },
    population: 313_000,
    wikidataId: 'Q1040',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'mannheim',
    name: 'Mannheim',
    nameLocal: 'Mannheim',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 49.4875, lng: 8.466 },
    population: 310_000,
    wikidataId: 'Q2119',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'augsburg',
    name: 'Augsburg',
    nameLocal: 'Augsburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bayern',
    coordinates: { lat: 48.3705, lng: 10.8978 },
    population: 300_000,
    wikidataId: 'Q2749',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'wiesbaden',
    name: 'Wiesbaden',
    nameLocal: 'Wiesbaden',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Hessen',
    coordinates: { lat: 50.0782, lng: 8.2398 },
    population: 278_000,
    wikidataId: 'Q1721',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'unna',
    name: 'Unna',
    nameLocal: 'Unna',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.5347, lng: 7.6889 },
    population: 59_000,
    wikidataId: 'Q7896',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'gelsenkirchen',
    name: 'Gelsenkirchen',
    nameLocal: 'Gelsenkirchen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.5177, lng: 7.0857 },
    population: 260_000,
    wikidataId: 'Q2765',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'moenchengladbach',
    name: 'Mönchengladbach',
    nameLocal: 'Mönchengladbach',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.1805, lng: 6.4428 },
    population: 261_000,
    wikidataId: 'Q2844',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'braunschweig',
    name: 'Braunschweig',
    nameLocal: 'Braunschweig',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Niedersachsen',
    coordinates: { lat: 52.2689, lng: 10.5268 },
    population: 249_000,
    wikidataId: 'Q2773',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'kiel',
    name: 'Kiel',
    nameLocal: 'Kiel',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Schleswig-Holstein',
    coordinates: { lat: 54.3233, lng: 10.1228 },
    population: 247_000,
    wikidataId: 'Q1706',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'chemnitz',
    name: 'Chemnitz',
    nameLocal: 'Chemnitz',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Sachsen',
    coordinates: { lat: 50.8278, lng: 12.9214 },
    population: 246_000,
    wikidataId: 'Q2795',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'aachen',
    name: 'Aachen',
    nameLocal: 'Aachen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 50.7753, lng: 6.0839 },
    population: 249_000,
    wikidataId: 'Q1017',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'halle',
    name: 'Halle',
    nameLocal: 'Halle (Saale)',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Sachsen-Anhalt',
    coordinates: { lat: 51.4828, lng: 11.97 },
    population: 239_000,
    wikidataId: 'Q2814',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'magdeburg',
    name: 'Magdeburg',
    nameLocal: 'Magdeburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Sachsen-Anhalt',
    coordinates: { lat: 52.1205, lng: 11.6276 },
    population: 236_000,
    wikidataId: 'Q1733',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'freiburg',
    name: 'Freiburg',
    nameLocal: 'Freiburg im Breisgau',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 47.999, lng: 7.842 },
    population: 231_000,
    wikidataId: 'Q2833',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'krefeld',
    name: 'Krefeld',
    nameLocal: 'Krefeld',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.3388, lng: 6.5853 },
    population: 228_000,
    wikidataId: 'Q2858',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'luebeck',
    name: 'Lübeck',
    nameLocal: 'Lübeck',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Schleswig-Holstein',
    coordinates: { lat: 53.8655, lng: 10.6866 },
    population: 217_000,
    wikidataId: 'Q2774',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'oberhausen',
    name: 'Oberhausen',
    nameLocal: 'Oberhausen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.4963, lng: 6.8625 },
    population: 210_000,
    wikidataId: 'Q2860',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'erfurt',
    name: 'Erfurt',
    nameLocal: 'Erfurt',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Thüringen',
    coordinates: { lat: 50.9787, lng: 11.0328 },
    population: 214_000,
    wikidataId: 'Q1729',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'mainz',
    name: 'Mainz',
    nameLocal: 'Mainz',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Rheinland-Pfalz',
    coordinates: { lat: 49.9929, lng: 8.2473 },
    population: 218_000,
    wikidataId: 'Q1720',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'rostock',
    name: 'Rostock',
    nameLocal: 'Rostock',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Mecklenburg-Vorpommern',
    coordinates: { lat: 54.0924, lng: 12.0991 },
    population: 209_000,
    wikidataId: 'Q2871',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'kassel',
    name: 'Kassel',
    nameLocal: 'Kassel',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Hessen',
    coordinates: { lat: 51.3127, lng: 9.4797 },
    population: 202_000,
    wikidataId: 'Q2865',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'hagen',
    name: 'Hagen',
    nameLocal: 'Hagen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.3671, lng: 7.4633 },
    population: 189_000,
    wikidataId: 'Q2876',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'saarbruecken',
    name: 'Saarbrücken',
    nameLocal: 'Saarbrücken',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Saarland',
    coordinates: { lat: 49.2402, lng: 6.9969 },
    population: 181_000,
    wikidataId: 'Q1724',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'hamm',
    name: 'Hamm',
    nameLocal: 'Hamm',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.6739, lng: 7.8159 },
    population: 179_000,
    wikidataId: 'Q2856',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'potsdam',
    name: 'Potsdam',
    nameLocal: 'Potsdam',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Brandenburg',
    coordinates: { lat: 52.3906, lng: 13.0645 },
    population: 183_000,
    wikidataId: 'Q1711',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'ludwigshafen',
    name: 'Ludwigshafen',
    nameLocal: 'Ludwigshafen am Rhein',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Rheinland-Pfalz',
    coordinates: { lat: 49.4774, lng: 8.445 },
    population: 172_000,
    wikidataId: 'Q2910',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'oldenburg',
    name: 'Oldenburg',
    nameLocal: 'Oldenburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Niedersachsen',
    coordinates: { lat: 53.1435, lng: 8.2146 },
    population: 170_000,
    wikidataId: 'Q7148',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'leverkusen',
    name: 'Leverkusen',
    nameLocal: 'Leverkusen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.0459, lng: 6.9844 },
    population: 163_000,
    wikidataId: 'Q2929',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'osnabrueck',
    name: 'Osnabrück',
    nameLocal: 'Osnabrück',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Niedersachsen',
    coordinates: { lat: 52.2799, lng: 8.0472 },
    population: 165_000,
    wikidataId: 'Q2939',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'solingen',
    name: 'Solingen',
    nameLocal: 'Solingen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.1652, lng: 7.0671 },
    population: 159_000,
    wikidataId: 'Q2943',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'heidelberg',
    name: 'Heidelberg',
    nameLocal: 'Heidelberg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 49.3988, lng: 8.6724 },
    population: 162_000,
    wikidataId: 'Q2966',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'darmstadt',
    name: 'Darmstadt',
    nameLocal: 'Darmstadt',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Hessen',
    coordinates: { lat: 49.8728, lng: 8.6512 },
    population: 159_000,
    wikidataId: 'Q2973',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'regensburg',
    name: 'Regensburg',
    nameLocal: 'Regensburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bayern',
    coordinates: { lat: 49.0134, lng: 12.1016 },
    population: 153_000,
    wikidataId: 'Q2978',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'ingolstadt',
    name: 'Ingolstadt',
    nameLocal: 'Ingolstadt',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bayern',
    coordinates: { lat: 48.7665, lng: 11.4258 },
    population: 140_000,
    wikidataId: 'Q2983',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'wuerzburg',
    name: 'Würzburg',
    nameLocal: 'Würzburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Bayern',
    coordinates: { lat: 49.7913, lng: 9.9534 },
    population: 128_000,
    wikidataId: 'Q3869',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'ulm',
    name: 'Ulm',
    nameLocal: 'Ulm',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 48.4011, lng: 9.9876 },
    population: 127_000,
    wikidataId: 'Q3012',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'wolfsburg',
    name: 'Wolfsburg',
    nameLocal: 'Wolfsburg',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Niedersachsen',
    coordinates: { lat: 52.4227, lng: 10.7865 },
    population: 125_000,
    wikidataId: 'Q3017',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'goettingen',
    name: 'Göttingen',
    nameLocal: 'Göttingen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Niedersachsen',
    coordinates: { lat: 51.5328, lng: 9.9352 },
    population: 119_000,
    wikidataId: 'Q3033',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'recklinghausen',
    name: 'Recklinghausen',
    nameLocal: 'Recklinghausen',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.614, lng: 7.198 },
    population: 112_000,
    wikidataId: 'Q2925',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'heilbronn',
    name: 'Heilbronn',
    nameLocal: 'Heilbronn',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Baden-Württemberg',
    coordinates: { lat: 49.1427, lng: 9.2109 },
    population: 128_000,
    wikidataId: 'Q3035',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },

  // ==========================================================================
  // AUSTRIA (8 cities)
  // ==========================================================================
  {
    slug: 'wien',
    name: 'Wien',
    nameLocal: 'Wien',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Wien',
    coordinates: { lat: 48.2082, lng: 16.3738 },
    population: 1_982_000,
    wikidataId: 'Q1741',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'graz',
    name: 'Graz',
    nameLocal: 'Graz',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Steiermark',
    coordinates: { lat: 47.0707, lng: 15.4395 },
    population: 295_000,
    wikidataId: 'Q13298',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'linz',
    name: 'Linz',
    nameLocal: 'Linz',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Oberösterreich',
    coordinates: { lat: 48.3069, lng: 14.2858 },
    population: 208_000,
    wikidataId: 'Q41329',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'salzburg',
    name: 'Salzburg',
    nameLocal: 'Salzburg',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Salzburg',
    coordinates: { lat: 47.8095, lng: 13.055 },
    population: 155_000,
    wikidataId: 'Q34713',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'innsbruck',
    name: 'Innsbruck',
    nameLocal: 'Innsbruck',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Tirol',
    coordinates: { lat: 47.2692, lng: 11.4041 },
    population: 132_000,
    wikidataId: 'Q1735',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'klagenfurt',
    name: 'Klagenfurt',
    nameLocal: 'Klagenfurt am Wörthersee',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Kärnten',
    coordinates: { lat: 46.6247, lng: 14.3053 },
    population: 102_000,
    wikidataId: 'Q41753',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'villach',
    name: 'Villach',
    nameLocal: 'Villach',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Kärnten',
    coordinates: { lat: 46.6111, lng: 13.8558 },
    population: 64_000,
    wikidataId: 'Q58863',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'wels',
    name: 'Wels',
    nameLocal: 'Wels',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Oberösterreich',
    coordinates: { lat: 48.1575, lng: 14.0289 },
    population: 63_000,
    wikidataId: 'Q252983',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },

  // ==========================================================================
  // SWITZERLAND (8 cities)
  // ==========================================================================
  {
    slug: 'zuerich',
    name: 'Zürich',
    nameLocal: 'Zürich',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Zürich',
    coordinates: { lat: 47.3769, lng: 8.5417 },
    population: 434_000,
    wikidataId: 'Q72',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },
  {
    slug: 'basel',
    name: 'Basel',
    nameLocal: 'Basel',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Basel-Stadt',
    coordinates: { lat: 47.5596, lng: 7.5886 },
    population: 178_000,
    wikidataId: 'Q78',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },
  {
    slug: 'bern',
    name: 'Bern',
    nameLocal: 'Bern',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Bern',
    coordinates: { lat: 46.948, lng: 7.4474 },
    population: 134_000,
    wikidataId: 'Q70',
    timezone: 'Europe/Zurich',
    languages: ['de', 'fr'],
  },
  {
    slug: 'genf',
    name: 'Genf',
    nameLocal: 'Genève',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Genève',
    coordinates: { lat: 46.2044, lng: 6.1432 },
    population: 203_000,
    wikidataId: 'Q71',
    timezone: 'Europe/Zurich',
    languages: ['fr'],
  },
  {
    slug: 'lausanne',
    name: 'Lausanne',
    nameLocal: 'Lausanne',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Vaud',
    coordinates: { lat: 46.5197, lng: 6.6323 },
    population: 140_000,
    wikidataId: 'Q807',
    timezone: 'Europe/Zurich',
    languages: ['fr'],
  },
  {
    slug: 'winterthur',
    name: 'Winterthur',
    nameLocal: 'Winterthur',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Zürich',
    coordinates: { lat: 47.4984, lng: 8.7246 },
    population: 115_000,
    wikidataId: 'Q9125',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },
  {
    slug: 'st-gallen',
    name: 'St. Gallen',
    nameLocal: 'St. Gallen',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'St. Gallen',
    coordinates: { lat: 47.4245, lng: 9.3767 },
    population: 76_000,
    wikidataId: 'Q43093',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },
  {
    slug: 'luzern',
    name: 'Luzern',
    nameLocal: 'Luzern',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Luzern',
    coordinates: { lat: 47.0502, lng: 8.3093 },
    population: 82_000,
    wikidataId: 'Q4191',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },

  // ==========================================================================
  // INTERNATIONAL — Europe (22 cities)
  // ==========================================================================
  {
    slug: 'london',
    name: 'London',
    nameLocal: 'London',
    country: 'Vereinigtes Königreich',
    countryCode: 'GB',
    region: 'England',
    coordinates: { lat: 51.5074, lng: -0.1278 },
    population: 8_982_000,
    wikidataId: 'Q84',
    timezone: 'Europe/London',
    languages: ['en'],
  },
  {
    slug: 'paris',
    name: 'Paris',
    nameLocal: 'Paris',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Île-de-France',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    population: 2_161_000,
    wikidataId: 'Q90',
    timezone: 'Europe/Paris',
    languages: ['fr'],
  },
  {
    slug: 'amsterdam',
    name: 'Amsterdam',
    nameLocal: 'Amsterdam',
    country: 'Niederlande',
    countryCode: 'NL',
    region: 'Noord-Holland',
    coordinates: { lat: 52.3676, lng: 4.9041 },
    population: 882_000,
    wikidataId: 'Q727',
    timezone: 'Europe/Amsterdam',
    languages: ['nl'],
  },
  {
    slug: 'barcelona',
    name: 'Barcelona',
    nameLocal: 'Barcelona',
    country: 'Spanien',
    countryCode: 'ES',
    region: 'Katalonien',
    coordinates: { lat: 41.3874, lng: 2.1686 },
    population: 1_636_000,
    wikidataId: 'Q1492',
    timezone: 'Europe/Madrid',
    languages: ['es', 'ca'],
  },
  {
    slug: 'madrid',
    name: 'Madrid',
    nameLocal: 'Madrid',
    country: 'Spanien',
    countryCode: 'ES',
    region: 'Comunidad de Madrid',
    coordinates: { lat: 40.4168, lng: -3.7038 },
    population: 3_305_000,
    wikidataId: 'Q2807',
    timezone: 'Europe/Madrid',
    languages: ['es'],
  },
  {
    slug: 'rom',
    name: 'Rom',
    nameLocal: 'Roma',
    country: 'Italien',
    countryCode: 'IT',
    region: 'Latium',
    coordinates: { lat: 41.9028, lng: 12.4964 },
    population: 2_873_000,
    wikidataId: 'Q220',
    timezone: 'Europe/Rome',
    languages: ['it'],
  },
  {
    slug: 'mailand',
    name: 'Mailand',
    nameLocal: 'Milano',
    country: 'Italien',
    countryCode: 'IT',
    region: 'Lombardei',
    coordinates: { lat: 45.4642, lng: 9.19 },
    population: 1_397_000,
    wikidataId: 'Q490',
    timezone: 'Europe/Rome',
    languages: ['it'],
  },
  {
    slug: 'stockholm',
    name: 'Stockholm',
    nameLocal: 'Stockholm',
    country: 'Schweden',
    countryCode: 'SE',
    region: 'Stockholm',
    coordinates: { lat: 59.3293, lng: 18.0686 },
    population: 984_000,
    wikidataId: 'Q1754',
    timezone: 'Europe/Stockholm',
    languages: ['sv'],
  },
  {
    slug: 'kopenhagen',
    name: 'Kopenhagen',
    nameLocal: 'København',
    country: 'Dänemark',
    countryCode: 'DK',
    region: 'Hovedstaden',
    coordinates: { lat: 55.6761, lng: 12.5683 },
    population: 644_000,
    wikidataId: 'Q1748',
    timezone: 'Europe/Copenhagen',
    languages: ['da'],
  },
  {
    slug: 'oslo',
    name: 'Oslo',
    nameLocal: 'Oslo',
    country: 'Norwegen',
    countryCode: 'NO',
    region: 'Oslo',
    coordinates: { lat: 59.9139, lng: 10.7522 },
    population: 697_000,
    wikidataId: 'Q585',
    timezone: 'Europe/Oslo',
    languages: ['no'],
  },
  {
    slug: 'helsinki',
    name: 'Helsinki',
    nameLocal: 'Helsinki',
    country: 'Finnland',
    countryCode: 'FI',
    region: 'Uusimaa',
    coordinates: { lat: 60.1699, lng: 24.9384 },
    population: 658_000,
    wikidataId: 'Q1757',
    timezone: 'Europe/Helsinki',
    languages: ['fi', 'sv'],
  },
  {
    slug: 'warschau',
    name: 'Warschau',
    nameLocal: 'Warszawa',
    country: 'Polen',
    countryCode: 'PL',
    region: 'Masowien',
    coordinates: { lat: 52.2297, lng: 21.0122 },
    population: 1_794_000,
    wikidataId: 'Q270',
    timezone: 'Europe/Warsaw',
    languages: ['pl'],
  },
  {
    slug: 'prag',
    name: 'Prag',
    nameLocal: 'Praha',
    country: 'Tschechien',
    countryCode: 'CZ',
    region: 'Hlavní město Praha',
    coordinates: { lat: 50.0755, lng: 14.4378 },
    population: 1_335_000,
    wikidataId: 'Q1085',
    timezone: 'Europe/Prague',
    languages: ['cs'],
  },
  {
    slug: 'budapest',
    name: 'Budapest',
    nameLocal: 'Budapest',
    country: 'Ungarn',
    countryCode: 'HU',
    region: 'Budapest',
    coordinates: { lat: 47.4979, lng: 19.0402 },
    population: 1_752_000,
    wikidataId: 'Q1781',
    timezone: 'Europe/Budapest',
    languages: ['hu'],
  },
  {
    slug: 'bruessel',
    name: 'Brüssel',
    nameLocal: 'Bruxelles',
    country: 'Belgien',
    countryCode: 'BE',
    region: 'Brüssel-Hauptstadt',
    coordinates: { lat: 50.8503, lng: 4.3517 },
    population: 1_222_000,
    wikidataId: 'Q239',
    timezone: 'Europe/Brussels',
    languages: ['nl', 'fr', 'de'],
  },
  {
    slug: 'dublin',
    name: 'Dublin',
    nameLocal: 'Dublin',
    country: 'Irland',
    countryCode: 'IE',
    region: 'Leinster',
    coordinates: { lat: 53.3498, lng: -6.2603 },
    population: 554_000,
    wikidataId: 'Q1761',
    timezone: 'Europe/Dublin',
    languages: ['en', 'ga'],
  },
  {
    slug: 'lissabon',
    name: 'Lissabon',
    nameLocal: 'Lisboa',
    country: 'Portugal',
    countryCode: 'PT',
    region: 'Lissabon',
    coordinates: { lat: 38.7223, lng: -9.1393 },
    population: 545_000,
    wikidataId: 'Q597',
    timezone: 'Europe/Lisbon',
    languages: ['pt'],
  },
  {
    slug: 'athen',
    name: 'Athen',
    nameLocal: 'Αθήνα',
    country: 'Griechenland',
    countryCode: 'GR',
    region: 'Attika',
    coordinates: { lat: 37.9838, lng: 23.7275 },
    population: 664_000,
    wikidataId: 'Q1524',
    timezone: 'Europe/Athens',
    languages: ['el'],
  },
  {
    slug: 'istanbul',
    name: 'Istanbul',
    nameLocal: 'İstanbul',
    country: 'Türkei',
    countryCode: 'TR',
    region: 'Istanbul',
    coordinates: { lat: 41.0082, lng: 28.9784 },
    population: 15_840_000,
    wikidataId: 'Q406',
    timezone: 'Europe/Istanbul',
    languages: ['tr'],
  },
  {
    slug: 'moskau',
    name: 'Moskau',
    nameLocal: 'Москва',
    country: 'Russland',
    countryCode: 'RU',
    region: 'Moskau',
    coordinates: { lat: 55.7558, lng: 37.6173 },
    population: 12_655_000,
    wikidataId: 'Q649',
    timezone: 'Europe/Moscow',
    languages: ['ru'],
  },
  {
    slug: 'st-petersburg',
    name: 'St. Petersburg',
    nameLocal: 'Санкт-Петербург',
    country: 'Russland',
    countryCode: 'RU',
    region: 'Nordwestrussland',
    coordinates: { lat: 59.9343, lng: 30.3351 },
    population: 5_384_000,
    wikidataId: 'Q656',
    timezone: 'Europe/Moscow',
    languages: ['ru'],
  },
  {
    slug: 'edinburgh',
    name: 'Edinburgh',
    nameLocal: 'Edinburgh',
    country: 'Vereinigtes Königreich',
    countryCode: 'GB',
    region: 'Schottland',
    coordinates: { lat: 55.9533, lng: -3.1883 },
    population: 527_000,
    wikidataId: 'Q23436',
    timezone: 'Europe/London',
    languages: ['en', 'gd'],
  },
  {
    slug: 'manchester',
    name: 'Manchester',
    nameLocal: 'Manchester',
    country: 'Vereinigtes Königreich',
    countryCode: 'GB',
    region: 'England',
    coordinates: { lat: 53.4808, lng: -2.2426 },
    population: 553_000,
    wikidataId: 'Q18125',
    timezone: 'Europe/London',
    languages: ['en'],
  },

  // ==========================================================================
  // INTERNATIONAL — Middle East & Africa (5 cities)
  // ==========================================================================
  {
    slug: 'dubai',
    name: 'Dubai',
    nameLocal: 'دبي',
    country: 'Vereinigte Arabische Emirate',
    countryCode: 'AE',
    region: 'Dubai',
    coordinates: { lat: 25.2048, lng: 55.2708 },
    population: 3_478_000,
    wikidataId: 'Q612',
    timezone: 'Asia/Dubai',
    languages: ['ar', 'en'],
  },
  {
    slug: 'kapstadt',
    name: 'Kapstadt',
    nameLocal: 'Cape Town',
    country: 'Südafrika',
    countryCode: 'ZA',
    region: 'Westkap',
    coordinates: { lat: -33.9249, lng: 18.4241 },
    population: 4_618_000,
    wikidataId: 'Q5465',
    timezone: 'Africa/Johannesburg',
    languages: ['af', 'en', 'xh'],
  },
  {
    slug: 'kairo',
    name: 'Kairo',
    nameLocal: 'القاهرة',
    country: 'Ägypten',
    countryCode: 'EG',
    region: 'Kairo',
    coordinates: { lat: 30.0444, lng: 31.2357 },
    population: 10_025_000,
    wikidataId: 'Q85',
    timezone: 'Africa/Cairo',
    languages: ['ar'],
  },
  {
    slug: 'nairobi',
    name: 'Nairobi',
    nameLocal: 'Nairobi',
    country: 'Kenia',
    countryCode: 'KE',
    region: 'Nairobi',
    coordinates: { lat: -1.2921, lng: 36.8219 },
    population: 4_397_000,
    wikidataId: 'Q3870',
    timezone: 'Africa/Nairobi',
    languages: ['sw', 'en'],
  },
  {
    slug: 'lagos',
    name: 'Lagos',
    nameLocal: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    region: 'Lagos',
    coordinates: { lat: 6.5244, lng: 3.3792 },
    population: 9_000_000,
    wikidataId: 'Q8673',
    timezone: 'Africa/Lagos',
    languages: ['en', 'yo'],
  },

  // ==========================================================================
  // INTERNATIONAL — Americas (11 cities)
  // ==========================================================================
  {
    slug: 'new-york',
    name: 'New York',
    nameLocal: 'New York',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'New York',
    coordinates: { lat: 40.7128, lng: -74.006 },
    population: 8_336_000,
    wikidataId: 'Q60',
    timezone: 'America/New_York',
    languages: ['en'],
  },
  {
    slug: 'los-angeles',
    name: 'Los Angeles',
    nameLocal: 'Los Angeles',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Kalifornien',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    population: 3_898_000,
    wikidataId: 'Q65',
    timezone: 'America/Los_Angeles',
    languages: ['en'],
  },
  {
    slug: 'san-francisco',
    name: 'San Francisco',
    nameLocal: 'San Francisco',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Kalifornien',
    coordinates: { lat: 37.7749, lng: -122.4194 },
    population: 874_000,
    wikidataId: 'Q62',
    timezone: 'America/Los_Angeles',
    languages: ['en'],
  },
  {
    slug: 'toronto',
    name: 'Toronto',
    nameLocal: 'Toronto',
    country: 'Kanada',
    countryCode: 'CA',
    region: 'Ontario',
    coordinates: { lat: 43.6532, lng: -79.3832 },
    population: 2_794_000,
    wikidataId: 'Q172',
    timezone: 'America/Toronto',
    languages: ['en', 'fr'],
  },
  {
    slug: 'chicago',
    name: 'Chicago',
    nameLocal: 'Chicago',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Illinois',
    coordinates: { lat: 41.8781, lng: -87.6298 },
    population: 2_696_000,
    wikidataId: 'Q1297',
    timezone: 'America/Chicago',
    languages: ['en'],
  },
  {
    slug: 'miami',
    name: 'Miami',
    nameLocal: 'Miami',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Florida',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    population: 442_000,
    wikidataId: 'Q8652',
    timezone: 'America/New_York',
    languages: ['en', 'es'],
  },
  {
    slug: 'seattle',
    name: 'Seattle',
    nameLocal: 'Seattle',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Washington',
    coordinates: { lat: 47.6062, lng: -122.3321 },
    population: 749_000,
    wikidataId: 'Q5083',
    timezone: 'America/Los_Angeles',
    languages: ['en'],
  },
  {
    slug: 'boston',
    name: 'Boston',
    nameLocal: 'Boston',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Massachusetts',
    coordinates: { lat: 42.3601, lng: -71.0589 },
    population: 675_000,
    wikidataId: 'Q100',
    timezone: 'America/New_York',
    languages: ['en'],
  },
  {
    slug: 'denver',
    name: 'Denver',
    nameLocal: 'Denver',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Colorado',
    coordinates: { lat: 39.7392, lng: -104.9903 },
    population: 715_000,
    wikidataId: 'Q16554',
    timezone: 'America/Denver',
    languages: ['en'],
  },
  {
    slug: 'austin',
    name: 'Austin',
    nameLocal: 'Austin',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'Texas',
    coordinates: { lat: 30.2672, lng: -97.7431 },
    population: 978_000,
    wikidataId: 'Q16559',
    timezone: 'America/Chicago',
    languages: ['en'],
  },
  {
    slug: 'vancouver',
    name: 'Vancouver',
    nameLocal: 'Vancouver',
    country: 'Kanada',
    countryCode: 'CA',
    region: 'British Columbia',
    coordinates: { lat: 49.2827, lng: -123.1207 },
    population: 662_000,
    wikidataId: 'Q24639',
    timezone: 'America/Vancouver',
    languages: ['en'],
  },
  {
    slug: 'buenos-aires',
    name: 'Buenos Aires',
    nameLocal: 'Buenos Aires',
    country: 'Argentinien',
    countryCode: 'AR',
    region: 'Buenos Aires',
    coordinates: { lat: -34.6037, lng: -58.3816 },
    population: 3_075_000,
    wikidataId: 'Q1486',
    timezone: 'America/Argentina/Buenos_Aires',
    languages: ['es'],
  },
  {
    slug: 'sao-paulo',
    name: 'São Paulo',
    nameLocal: 'São Paulo',
    country: 'Brasilien',
    countryCode: 'BR',
    region: 'São Paulo',
    coordinates: { lat: -23.5505, lng: -46.6333 },
    population: 12_325_000,
    wikidataId: 'Q174',
    timezone: 'America/Sao_Paulo',
    languages: ['pt'],
  },
  {
    slug: 'mexiko-stadt',
    name: 'Mexiko-Stadt',
    nameLocal: 'Ciudad de México',
    country: 'Mexiko',
    countryCode: 'MX',
    region: 'Ciudad de México',
    coordinates: { lat: 19.4326, lng: -99.1332 },
    population: 9_209_000,
    wikidataId: 'Q1489',
    timezone: 'America/Mexico_City',
    languages: ['es'],
  },
  {
    slug: 'lima',
    name: 'Lima',
    nameLocal: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    region: 'Lima',
    coordinates: { lat: -12.0464, lng: -77.0428 },
    population: 9_751_000,
    wikidataId: 'Q2868',
    timezone: 'America/Lima',
    languages: ['es'],
  },

  // ==========================================================================
  // INTERNATIONAL — Asia-Pacific (11 cities)
  // ==========================================================================
  {
    slug: 'singapur',
    name: 'Singapur',
    nameLocal: 'Singapore',
    country: 'Singapur',
    countryCode: 'SG',
    region: 'Singapur',
    coordinates: { lat: 1.3521, lng: 103.8198 },
    population: 5_454_000,
    wikidataId: 'Q334',
    timezone: 'Asia/Singapore',
    languages: ['en', 'zh', 'ms', 'ta'],
  },
  {
    slug: 'tokio',
    name: 'Tokio',
    nameLocal: '東京',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Kantō',
    coordinates: { lat: 35.6762, lng: 139.6503 },
    population: 13_960_000,
    wikidataId: 'Q1490',
    timezone: 'Asia/Tokyo',
    languages: ['ja'],
  },
  {
    slug: 'mumbai',
    name: 'Mumbai',
    nameLocal: 'मुंबई',
    country: 'Indien',
    countryCode: 'IN',
    region: 'Maharashtra',
    coordinates: { lat: 19.076, lng: 72.8777 },
    population: 12_478_000,
    wikidataId: 'Q1156',
    timezone: 'Asia/Kolkata',
    languages: ['hi', 'mr', 'en'],
  },
  {
    slug: 'sydney',
    name: 'Sydney',
    nameLocal: 'Sydney',
    country: 'Australien',
    countryCode: 'AU',
    region: 'New South Wales',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    population: 5_312_000,
    wikidataId: 'Q3130',
    timezone: 'Australia/Sydney',
    languages: ['en'],
  },
  {
    slug: 'melbourne',
    name: 'Melbourne',
    nameLocal: 'Melbourne',
    country: 'Australien',
    countryCode: 'AU',
    region: 'Victoria',
    coordinates: { lat: -37.8136, lng: 144.9631 },
    population: 5_078_000,
    wikidataId: 'Q3141',
    timezone: 'Australia/Melbourne',
    languages: ['en'],
  },
  {
    slug: 'bangkok',
    name: 'Bangkok',
    nameLocal: 'กรุงเทพมหานคร',
    country: 'Thailand',
    countryCode: 'TH',
    region: 'Bangkok',
    coordinates: { lat: 13.7563, lng: 100.5018 },
    population: 5_676_000,
    wikidataId: 'Q1861',
    timezone: 'Asia/Bangkok',
    languages: ['th'],
  },
  {
    slug: 'seoul',
    name: 'Seoul',
    nameLocal: '서울',
    country: 'Südkorea',
    countryCode: 'KR',
    region: 'Seoul',
    coordinates: { lat: 37.5665, lng: 126.978 },
    population: 9_776_000,
    wikidataId: 'Q8684',
    timezone: 'Asia/Seoul',
    languages: ['ko'],
  },
  {
    slug: 'shanghai',
    name: 'Shanghai',
    nameLocal: '上海',
    country: 'China',
    countryCode: 'CN',
    region: 'Shanghai',
    coordinates: { lat: 31.2304, lng: 121.4737 },
    population: 24_870_000,
    wikidataId: 'Q8686',
    timezone: 'Asia/Shanghai',
    languages: ['zh'],
  },
  {
    slug: 'peking',
    name: 'Peking',
    nameLocal: '北京',
    country: 'China',
    countryCode: 'CN',
    region: 'Peking',
    coordinates: { lat: 39.9042, lng: 116.4074 },
    population: 21_540_000,
    wikidataId: 'Q956',
    timezone: 'Asia/Shanghai',
    languages: ['zh'],
  },
  {
    slug: 'hongkong',
    name: 'Hongkong',
    nameLocal: '香港',
    country: 'Hongkong',
    countryCode: 'HK',
    region: 'Hongkong',
    coordinates: { lat: 22.3193, lng: 114.1694 },
    population: 7_482_000,
    wikidataId: 'Q8646',
    timezone: 'Asia/Hong_Kong',
    languages: ['zh', 'en'],
  },
  {
    slug: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    nameLocal: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    region: 'Kuala Lumpur',
    coordinates: { lat: 3.139, lng: 101.6869 },
    population: 1_982_000,
    wikidataId: 'Q1865',
    timezone: 'Asia/Kuala_Lumpur',
    languages: ['ms', 'en'],
  },
  {
    slug: 'jakarta',
    name: 'Jakarta',
    nameLocal: 'Jakarta',
    country: 'Indonesien',
    countryCode: 'ID',
    region: 'Jakarta',
    coordinates: { lat: -6.2088, lng: 106.8456 },
    population: 10_562_000,
    wikidataId: 'Q3630',
    timezone: 'Asia/Jakarta',
    languages: ['id'],
  },
  {
    slug: 'tel-aviv',
    name: 'Tel Aviv',
    nameLocal: 'תל אביב-יפו',
    country: 'Israel',
    countryCode: 'IL',
    region: 'Tel Aviv',
    coordinates: { lat: 32.0853, lng: 34.7818 },
    population: 460_000,
    wikidataId: 'Q33935',
    timezone: 'Asia/Jerusalem',
    languages: ['he', 'ar'],
  },

  // ==========================================================================
  // GERMANY — additional cities
  // ==========================================================================
  {
    slug: 'muelheim',
    name: 'Mülheim an der Ruhr',
    nameLocal: 'Mülheim an der Ruhr',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.4322, lng: 6.8825 },
    population: 171_000,
    wikidataId: 'Q2897',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'paderborn',
    name: 'Paderborn',
    nameLocal: 'Paderborn',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Nordrhein-Westfalen',
    coordinates: { lat: 51.7189, lng: 8.7575 },
    population: 155_000,
    wikidataId: 'Q2945',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },
  {
    slug: 'offenbach',
    name: 'Offenbach am Main',
    nameLocal: 'Offenbach am Main',
    country: 'Deutschland',
    countryCode: 'DE',
    region: 'Hessen',
    coordinates: { lat: 50.0956, lng: 8.7761 },
    population: 132_000,
    wikidataId: 'Q3953',
    timezone: 'Europe/Berlin',
    languages: ['de'],
  },

  // ==========================================================================
  // AUSTRIA — additional cities
  // ==========================================================================
  {
    slug: 'st-poelten',
    name: 'St. Pölten',
    nameLocal: 'St. Pölten',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Niederösterreich',
    coordinates: { lat: 48.2043, lng: 15.6229 },
    population: 56_000,
    wikidataId: 'Q41397',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'dornbirn',
    name: 'Dornbirn',
    nameLocal: 'Dornbirn',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Vorarlberg',
    coordinates: { lat: 47.4125, lng: 9.7417 },
    population: 50_000,
    wikidataId: 'Q82688',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'wiener-neustadt',
    name: 'Wiener Neustadt',
    nameLocal: 'Wiener Neustadt',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Niederösterreich',
    coordinates: { lat: 47.8151, lng: 16.2465 },
    population: 46_000,
    wikidataId: 'Q131838',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'steyr',
    name: 'Steyr',
    nameLocal: 'Steyr',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Oberösterreich',
    coordinates: { lat: 48.0427, lng: 14.4213 },
    population: 38_000,
    wikidataId: 'Q164370',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },
  {
    slug: 'feldkirch',
    name: 'Feldkirch',
    nameLocal: 'Feldkirch',
    country: 'Österreich',
    countryCode: 'AT',
    region: 'Vorarlberg',
    coordinates: { lat: 47.2333, lng: 9.6 },
    population: 35_000,
    wikidataId: 'Q82699',
    timezone: 'Europe/Vienna',
    languages: ['de'],
  },

  // ==========================================================================
  // SWITZERLAND — additional cities
  // ==========================================================================
  {
    slug: 'biel',
    name: 'Biel',
    nameLocal: 'Biel/Bienne',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Bern',
    coordinates: { lat: 47.1368, lng: 7.2467 },
    population: 55_000,
    wikidataId: 'Q1034',
    timezone: 'Europe/Zurich',
    languages: ['de', 'fr'],
  },
  {
    slug: 'thun',
    name: 'Thun',
    nameLocal: 'Thun',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Bern',
    coordinates: { lat: 46.758, lng: 7.628 },
    population: 44_000,
    wikidataId: 'Q69012',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },
  {
    slug: 'uster',
    name: 'Uster',
    nameLocal: 'Uster',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Zürich',
    coordinates: { lat: 47.3473, lng: 8.7216 },
    population: 36_000,
    wikidataId: 'Q68190',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },
  {
    slug: 'koeniz',
    name: 'Köniz',
    nameLocal: 'Köniz',
    country: 'Schweiz',
    countryCode: 'CH',
    region: 'Bern',
    coordinates: { lat: 46.9208, lng: 7.4153 },
    population: 43_000,
    wikidataId: 'Q68243',
    timezone: 'Europe/Zurich',
    languages: ['de'],
  },

  // ==========================================================================
  // INTERNATIONAL — Europe additional
  // ==========================================================================
  {
    slug: 'porto',
    name: 'Porto',
    nameLocal: 'Porto',
    country: 'Portugal',
    countryCode: 'PT',
    region: 'Porto',
    coordinates: { lat: 41.1579, lng: -8.6291 },
    population: 249_000,
    wikidataId: 'Q36433',
    timezone: 'Europe/Lisbon',
    languages: ['pt'],
  },
  {
    slug: 'thessaloniki',
    name: 'Thessaloniki',
    nameLocal: 'Θεσσαλονίκη',
    country: 'Griechenland',
    countryCode: 'GR',
    region: 'Zentralmakedonien',
    coordinates: { lat: 40.6401, lng: 22.9444 },
    population: 325_000,
    wikidataId: 'Q17151',
    timezone: 'Europe/Athens',
    languages: ['el'],
  },
  {
    slug: 'bukarest',
    name: 'Bukarest',
    nameLocal: 'București',
    country: 'Rumänien',
    countryCode: 'RO',
    region: 'București',
    coordinates: { lat: 44.4268, lng: 26.1025 },
    population: 1_794_000,
    wikidataId: 'Q19660',
    timezone: 'Europe/Bucharest',
    languages: ['ro'],
  },
  {
    slug: 'sofia',
    name: 'Sofia',
    nameLocal: 'София',
    country: 'Bulgarien',
    countryCode: 'BG',
    region: 'Sofia-Stadt',
    coordinates: { lat: 42.6977, lng: 23.3219 },
    population: 1_307_000,
    wikidataId: 'Q472',
    timezone: 'Europe/Sofia',
    languages: ['bg'],
  },
  {
    slug: 'zagreb',
    name: 'Zagreb',
    nameLocal: 'Zagreb',
    country: 'Kroatien',
    countryCode: 'HR',
    region: 'Zagreb',
    coordinates: { lat: 45.815, lng: 15.9819 },
    population: 807_000,
    wikidataId: 'Q1435',
    timezone: 'Europe/Zagreb',
    languages: ['hr'],
  },
  {
    slug: 'ljubljana',
    name: 'Ljubljana',
    nameLocal: 'Ljubljana',
    country: 'Slowenien',
    countryCode: 'SI',
    region: 'Osrednjeslovenska',
    coordinates: { lat: 46.0569, lng: 14.5058 },
    population: 295_000,
    wikidataId: 'Q437',
    timezone: 'Europe/Ljubljana',
    languages: ['sl'],
  },
  {
    slug: 'bratislava',
    name: 'Bratislava',
    nameLocal: 'Bratislava',
    country: 'Slowakei',
    countryCode: 'SK',
    region: 'Bratislava',
    coordinates: { lat: 48.1486, lng: 17.1077 },
    population: 475_000,
    wikidataId: 'Q1780',
    timezone: 'Europe/Bratislava',
    languages: ['sk'],
  },
  {
    slug: 'tallinn',
    name: 'Tallinn',
    nameLocal: 'Tallinn',
    country: 'Estland',
    countryCode: 'EE',
    region: 'Harju',
    coordinates: { lat: 59.437, lng: 24.7536 },
    population: 444_000,
    wikidataId: 'Q1770',
    timezone: 'Europe/Tallinn',
    languages: ['et'],
  },
  {
    slug: 'riga',
    name: 'Riga',
    nameLocal: 'Rīga',
    country: 'Lettland',
    countryCode: 'LV',
    region: 'Riga',
    coordinates: { lat: 56.9496, lng: 24.1052 },
    population: 614_000,
    wikidataId: 'Q1773',
    timezone: 'Europe/Riga',
    languages: ['lv'],
  },
  {
    slug: 'vilnius',
    name: 'Vilnius',
    nameLocal: 'Vilnius',
    country: 'Litauen',
    countryCode: 'LT',
    region: 'Vilnius',
    coordinates: { lat: 54.6872, lng: 25.2797 },
    population: 588_000,
    wikidataId: 'Q216',
    timezone: 'Europe/Vilnius',
    languages: ['lt'],
  },
  {
    slug: 'antwerpen',
    name: 'Antwerpen',
    nameLocal: 'Antwerpen',
    country: 'Belgien',
    countryCode: 'BE',
    region: 'Flandern',
    coordinates: { lat: 51.2194, lng: 4.4025 },
    population: 530_000,
    wikidataId: 'Q12892',
    timezone: 'Europe/Brussels',
    languages: ['nl'],
  },
  {
    slug: 'rotterdam',
    name: 'Rotterdam',
    nameLocal: 'Rotterdam',
    country: 'Niederlande',
    countryCode: 'NL',
    region: 'Zuid-Holland',
    coordinates: { lat: 51.9225, lng: 4.4792 },
    population: 651_000,
    wikidataId: 'Q34370',
    timezone: 'Europe/Amsterdam',
    languages: ['nl'],
  },
  {
    slug: 'den-haag',
    name: 'Den Haag',
    nameLocal: 'Den Haag',
    country: 'Niederlande',
    countryCode: 'NL',
    region: 'Zuid-Holland',
    coordinates: { lat: 52.0705, lng: 4.3007 },
    population: 548_000,
    wikidataId: 'Q36600',
    timezone: 'Europe/Amsterdam',
    languages: ['nl'],
  },
  {
    slug: 'utrecht',
    name: 'Utrecht',
    nameLocal: 'Utrecht',
    country: 'Niederlande',
    countryCode: 'NL',
    region: 'Utrecht',
    coordinates: { lat: 52.0907, lng: 5.1214 },
    population: 361_000,
    wikidataId: 'Q803',
    timezone: 'Europe/Amsterdam',
    languages: ['nl'],
  },
  {
    slug: 'eindhoven',
    name: 'Eindhoven',
    nameLocal: 'Eindhoven',
    country: 'Niederlande',
    countryCode: 'NL',
    region: 'Noord-Brabant',
    coordinates: { lat: 51.4416, lng: 5.4697 },
    population: 238_000,
    wikidataId: 'Q9832',
    timezone: 'Europe/Amsterdam',
    languages: ['nl'],
  },
  {
    slug: 'malmoe',
    name: 'Malmö',
    nameLocal: 'Malmö',
    country: 'Schweden',
    countryCode: 'SE',
    region: 'Skåne',
    coordinates: { lat: 55.605, lng: 13.0038 },
    population: 351_000,
    wikidataId: 'Q2211',
    timezone: 'Europe/Stockholm',
    languages: ['sv'],
  },
  {
    slug: 'goeteborg',
    name: 'Göteborg',
    nameLocal: 'Göteborg',
    country: 'Schweden',
    countryCode: 'SE',
    region: 'Västra Götaland',
    coordinates: { lat: 57.7089, lng: 11.9746 },
    population: 583_000,
    wikidataId: 'Q25287',
    timezone: 'Europe/Stockholm',
    languages: ['sv'],
  },
  {
    slug: 'turku',
    name: 'Turku',
    nameLocal: 'Turku',
    country: 'Finnland',
    countryCode: 'FI',
    region: 'Varsinais-Suomi',
    coordinates: { lat: 60.4518, lng: 22.2666 },
    population: 195_000,
    wikidataId: 'Q38511',
    timezone: 'Europe/Helsinki',
    languages: ['fi', 'sv'],
  },
  {
    slug: 'krakau',
    name: 'Krakau',
    nameLocal: 'Kraków',
    country: 'Polen',
    countryCode: 'PL',
    region: 'Kleinpolen',
    coordinates: { lat: 50.0647, lng: 19.945 },
    population: 800_000,
    wikidataId: 'Q31487',
    timezone: 'Europe/Warsaw',
    languages: ['pl'],
  },
  {
    slug: 'breslau',
    name: 'Breslau',
    nameLocal: 'Wrocław',
    country: 'Polen',
    countryCode: 'PL',
    region: 'Niederschlesien',
    coordinates: { lat: 51.1079, lng: 17.0385 },
    population: 673_000,
    wikidataId: 'Q1799',
    timezone: 'Europe/Warsaw',
    languages: ['pl'],
  },
  {
    slug: 'danzig',
    name: 'Danzig',
    nameLocal: 'Gdańsk',
    country: 'Polen',
    countryCode: 'PL',
    region: 'Pommern',
    coordinates: { lat: 54.352, lng: 18.6466 },
    population: 471_000,
    wikidataId: 'Q1792',
    timezone: 'Europe/Warsaw',
    languages: ['pl'],
  },
  {
    slug: 'poznan',
    name: 'Poznan',
    nameLocal: 'Poznań',
    country: 'Polen',
    countryCode: 'PL',
    region: 'Großpolen',
    coordinates: { lat: 52.4064, lng: 16.9252 },
    population: 534_000,
    wikidataId: 'Q268',
    timezone: 'Europe/Warsaw',
    languages: ['pl'],
  },
  {
    slug: 'lyon',
    name: 'Lyon',
    nameLocal: 'Lyon',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Auvergne-Rhône-Alpes',
    coordinates: { lat: 45.764, lng: 4.8357 },
    population: 522_000,
    wikidataId: 'Q456',
    timezone: 'Europe/Paris',
    languages: ['fr'],
  },
  {
    slug: 'marseille',
    name: 'Marseille',
    nameLocal: 'Marseille',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Provence-Alpes-Côte d\'Azur',
    coordinates: { lat: 43.2965, lng: 5.3698 },
    population: 870_000,
    wikidataId: 'Q2634',
    timezone: 'Europe/Paris',
    languages: ['fr'],
  },
  {
    slug: 'toulouse',
    name: 'Toulouse',
    nameLocal: 'Toulouse',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Okzitanien',
    coordinates: { lat: 43.6047, lng: 1.4442 },
    population: 493_000,
    wikidataId: 'Q7880',
    timezone: 'Europe/Paris',
    languages: ['fr'],
  },
  {
    slug: 'nizza',
    name: 'Nizza',
    nameLocal: 'Nice',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Provence-Alpes-Côte d\'Azur',
    coordinates: { lat: 43.7102, lng: 7.262 },
    population: 342_000,
    wikidataId: 'Q33959',
    timezone: 'Europe/Paris',
    languages: ['fr'],
  },
  {
    slug: 'bordeaux',
    name: 'Bordeaux',
    nameLocal: 'Bordeaux',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Nouvelle-Aquitaine',
    coordinates: { lat: 44.8378, lng: -0.5792 },
    population: 260_000,
    wikidataId: 'Q1479',
    timezone: 'Europe/Paris',
    languages: ['fr'],
  },
  {
    slug: 'strassburg',
    name: 'Straßburg',
    nameLocal: 'Strasbourg',
    country: 'Frankreich',
    countryCode: 'FR',
    region: 'Grand Est',
    coordinates: { lat: 48.5734, lng: 7.7521 },
    population: 284_000,
    wikidataId: 'Q6602',
    timezone: 'Europe/Paris',
    languages: ['fr', 'de'],
  },
  {
    slug: 'turin',
    name: 'Turin',
    nameLocal: 'Torino',
    country: 'Italien',
    countryCode: 'IT',
    region: 'Piemont',
    coordinates: { lat: 45.0703, lng: 7.6869 },
    population: 848_000,
    wikidataId: 'Q495',
    timezone: 'Europe/Rome',
    languages: ['it'],
  },
  {
    slug: 'florenz',
    name: 'Florenz',
    nameLocal: 'Firenze',
    country: 'Italien',
    countryCode: 'IT',
    region: 'Toskana',
    coordinates: { lat: 43.7696, lng: 11.2558 },
    population: 382_000,
    wikidataId: 'Q2044',
    timezone: 'Europe/Rome',
    languages: ['it'],
  },
  {
    slug: 'bologna',
    name: 'Bologna',
    nameLocal: 'Bologna',
    country: 'Italien',
    countryCode: 'IT',
    region: 'Emilia-Romagna',
    coordinates: { lat: 44.4949, lng: 11.3426 },
    population: 394_000,
    wikidataId: 'Q1891',
    timezone: 'Europe/Rome',
    languages: ['it'],
  },
  {
    slug: 'neapel',
    name: 'Neapel',
    nameLocal: 'Napoli',
    country: 'Italien',
    countryCode: 'IT',
    region: 'Kampanien',
    coordinates: { lat: 40.8518, lng: 14.2681 },
    population: 914_000,
    wikidataId: 'Q2634',
    timezone: 'Europe/Rome',
    languages: ['it'],
  },
  {
    slug: 'sevilla',
    name: 'Sevilla',
    nameLocal: 'Sevilla',
    country: 'Spanien',
    countryCode: 'ES',
    region: 'Andalusien',
    coordinates: { lat: 37.3891, lng: -5.9845 },
    population: 688_000,
    wikidataId: 'Q8717',
    timezone: 'Europe/Madrid',
    languages: ['es'],
  },
  {
    slug: 'valencia',
    name: 'Valencia',
    nameLocal: 'València',
    country: 'Spanien',
    countryCode: 'ES',
    region: 'Valencianische Gemeinschaft',
    coordinates: { lat: 39.4699, lng: -0.3763 },
    population: 792_000,
    wikidataId: 'Q8818',
    timezone: 'Europe/Madrid',
    languages: ['es', 'ca'],
  },
  {
    slug: 'bilbao',
    name: 'Bilbao',
    nameLocal: 'Bilbao',
    country: 'Spanien',
    countryCode: 'ES',
    region: 'Baskenland',
    coordinates: { lat: 43.263, lng: -2.935 },
    population: 346_000,
    wikidataId: 'Q8692',
    timezone: 'Europe/Madrid',
    languages: ['es', 'eu'],
  },

  // ==========================================================================
  // INTERNATIONAL — Americas additional
  // ==========================================================================
  {
    slug: 'montreal',
    name: 'Montreal',
    nameLocal: 'Montréal',
    country: 'Kanada',
    countryCode: 'CA',
    region: 'Québec',
    coordinates: { lat: 45.5017, lng: -73.5673 },
    population: 1_762_000,
    wikidataId: 'Q340',
    timezone: 'America/Toronto',
    languages: ['fr', 'en'],
  },
  {
    slug: 'washington',
    name: 'Washington',
    nameLocal: 'Washington, D.C.',
    country: 'Vereinigte Staaten',
    countryCode: 'US',
    region: 'District of Columbia',
    coordinates: { lat: 38.9072, lng: -77.0369 },
    population: 689_000,
    wikidataId: 'Q61',
    timezone: 'America/New_York',
    languages: ['en'],
  },

  // ==========================================================================
  // INTERNATIONAL — Asia-Pacific additional
  // ==========================================================================
  {
    slug: 'delhi',
    name: 'Delhi',
    nameLocal: 'दिल्ली',
    country: 'Indien',
    countryCode: 'IN',
    region: 'Delhi',
    coordinates: { lat: 28.7041, lng: 77.1025 },
    population: 11_035_000,
    wikidataId: 'Q987',
    timezone: 'Asia/Kolkata',
    languages: ['hi', 'en'],
  },
  {
    slug: 'taipeh',
    name: 'Taipeh',
    nameLocal: '臺北',
    country: 'Taiwan',
    countryCode: 'TW',
    region: 'Taipeh',
    coordinates: { lat: 25.033, lng: 121.5654 },
    population: 2_602_000,
    wikidataId: 'Q1867',
    timezone: 'Asia/Taipei',
    languages: ['zh'],
  },
  {
    slug: 'auckland',
    name: 'Auckland',
    nameLocal: 'Auckland',
    country: 'Neuseeland',
    countryCode: 'NZ',
    region: 'Auckland',
    coordinates: { lat: -36.8485, lng: 174.7633 },
    population: 1_657_000,
    wikidataId: 'Q37100',
    timezone: 'Pacific/Auckland',
    languages: ['en', 'mi'],
  },

  // ==========================================================================
  // INTERNATIONAL — Africa additional
  // ==========================================================================
  {
    slug: 'johannesburg',
    name: 'Johannesburg',
    nameLocal: 'Johannesburg',
    country: 'Südafrika',
    countryCode: 'ZA',
    region: 'Gauteng',
    coordinates: { lat: -26.2041, lng: 28.0473 },
    population: 5_783_000,
    wikidataId: 'Q34647',
    timezone: 'Africa/Johannesburg',
    languages: ['en', 'zu', 'af'],
  },
  { slug: 'trier', name: 'Trier', nameLocal: 'Trier', country: 'Deutschland', countryCode: 'DE', region: 'Rheinland-Pfalz', coordinates: { lat: 49.7490, lng: 6.6371 }, population: 111_000, wikidataId: 'Q3138', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'erlangen', name: 'Erlangen', nameLocal: 'Erlangen', country: 'Deutschland', countryCode: 'DE', region: 'Bayern', coordinates: { lat: 49.5897, lng: 11.0078 }, population: 113_000, wikidataId: 'Q3141', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'ulm', name: 'Ulm', nameLocal: 'Ulm', country: 'Deutschland', countryCode: 'DE', region: 'Baden-Württemberg', coordinates: { lat: 48.4011, lng: 9.9876 }, population: 127_000, wikidataId: 'Q3012', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'heilbronn', name: 'Heilbronn', nameLocal: 'Heilbronn', country: 'Deutschland', countryCode: 'DE', region: 'Baden-Württemberg', coordinates: { lat: 49.1427, lng: 9.2109 }, population: 127_000, wikidataId: 'Q3109', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'pforzheim', name: 'Pforzheim', nameLocal: 'Pforzheim', country: 'Deutschland', countryCode: 'DE', region: 'Baden-Württemberg', coordinates: { lat: 48.8922, lng: 8.6946 }, population: 125_000, wikidataId: 'Q3095', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'goettingen', name: 'Göttingen', nameLocal: 'Göttingen', country: 'Deutschland', countryCode: 'DE', region: 'Niedersachsen', coordinates: { lat: 51.5328, lng: 9.9355 }, population: 119_000, wikidataId: 'Q3033', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'reutlingen', name: 'Reutlingen', nameLocal: 'Reutlingen', country: 'Deutschland', countryCode: 'DE', region: 'Baden-Württemberg', coordinates: { lat: 48.4912, lng: 9.2043 }, population: 116_000, wikidataId: 'Q3200', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'koblenz', name: 'Koblenz', nameLocal: 'Koblenz', country: 'Deutschland', countryCode: 'DE', region: 'Rheinland-Pfalz', coordinates: { lat: 50.3569, lng: 7.5890 }, population: 114_000, wikidataId: 'Q3104', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'wolfsburg', name: 'Wolfsburg', nameLocal: 'Wolfsburg', country: 'Deutschland', countryCode: 'DE', region: 'Niedersachsen', coordinates: { lat: 52.4227, lng: 10.7865 }, population: 124_000, wikidataId: 'Q3014', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'bremerhaven', name: 'Bremerhaven', nameLocal: 'Bremerhaven', country: 'Deutschland', countryCode: 'DE', region: 'Bremen', coordinates: { lat: 53.5396, lng: 8.5809 }, population: 113_000, wikidataId: 'Q2982', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'bergisch-gladbach', name: 'Bergisch Gladbach', nameLocal: 'Bergisch Gladbach', country: 'Deutschland', countryCode: 'DE', region: 'Nordrhein-Westfalen', coordinates: { lat: 50.9919, lng: 7.1362 }, population: 112_000, wikidataId: 'Q3104', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'jena', name: 'Jena', nameLocal: 'Jena', country: 'Deutschland', countryCode: 'DE', region: 'Thüringen', coordinates: { lat: 50.9272, lng: 11.5892 }, population: 112_000, wikidataId: 'Q3150', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'hildesheim', name: 'Hildesheim', nameLocal: 'Hildesheim', country: 'Deutschland', countryCode: 'DE', region: 'Niedersachsen', coordinates: { lat: 52.1508, lng: 9.9517 }, population: 101_000, wikidataId: 'Q3187', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'cottbus', name: 'Cottbus', nameLocal: 'Cottbus', country: 'Deutschland', countryCode: 'DE', region: 'Brandenburg', coordinates: { lat: 51.7563, lng: 14.3329 }, population: 100_000, wikidataId: 'Q3214', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'siegen', name: 'Siegen', nameLocal: 'Siegen', country: 'Deutschland', countryCode: 'DE', region: 'Nordrhein-Westfalen', coordinates: { lat: 50.8838, lng: 8.0243 }, population: 102_000, wikidataId: 'Q3166', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'salzgitter', name: 'Salzgitter', nameLocal: 'Salzgitter', country: 'Deutschland', countryCode: 'DE', region: 'Niedersachsen', coordinates: { lat: 52.1556, lng: 10.3328 }, population: 106_000, wikidataId: 'Q3167', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'schwerin', name: 'Schwerin', nameLocal: 'Schwerin', country: 'Deutschland', countryCode: 'DE', region: 'Mecklenburg-Vorpommern', coordinates: { lat: 53.6355, lng: 11.4012 }, population: 96_000, wikidataId: 'Q3218', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'plauen', name: 'Plauen', nameLocal: 'Plauen', country: 'Deutschland', countryCode: 'DE', region: 'Sachsen', coordinates: { lat: 50.4957, lng: 12.1343 }, population: 65_000, wikidataId: 'Q3169', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'lima', name: 'Lima', nameLocal: 'Lima', country: 'Peru', countryCode: 'PE', region: 'Lima', coordinates: { lat: -12.0464, lng: -77.0428 }, population: 10_882_000, wikidataId: 'Q2868', timezone: 'America/Lima', languages: ['es'] },
  { slug: 'bogota', name: 'Bogota', nameLocal: 'Bogotá', country: 'Kolumbien', countryCode: 'CO', region: 'Cundinamarca', coordinates: { lat: 4.7110, lng: -74.0721 }, population: 7_181_000, wikidataId: 'Q2841', timezone: 'America/Bogota', languages: ['es'] },
  { slug: 'mexiko-stadt', name: 'Mexiko-Stadt', nameLocal: 'Ciudad de México', country: 'Mexiko', countryCode: 'MX', region: 'CDMX', coordinates: { lat: 19.4326, lng: -99.1332 }, population: 9_209_000, wikidataId: 'Q1489', timezone: 'America/Mexico_City', languages: ['es'] },
  { slug: 'buenos-aires', name: 'Buenos Aires', nameLocal: 'Buenos Aires', country: 'Argentinien', countryCode: 'AR', region: 'Buenos Aires', coordinates: { lat: -34.6037, lng: -58.3816 }, population: 3_075_000, wikidataId: 'Q1486', timezone: 'America/Argentina/Buenos_Aires', languages: ['es'] },
  { slug: 'santiago', name: 'Santiago', nameLocal: 'Santiago de Chile', country: 'Chile', countryCode: 'CL', region: 'Santiago Metropolitan', coordinates: { lat: -33.4489, lng: -70.6693 }, population: 5_614_000, wikidataId: 'Q2887', timezone: 'America/Santiago', languages: ['es'] },
  { slug: 'nairobi', name: 'Nairobi', nameLocal: 'Nairobi', country: 'Kenia', countryCode: 'KE', region: 'Nairobi County', coordinates: { lat: -1.2921, lng: 36.8219 }, population: 4_397_000, wikidataId: 'Q3870', timezone: 'Africa/Nairobi', languages: ['sw', 'en'] },
  { slug: 'lagos', name: 'Lagos', nameLocal: 'Lagos', country: 'Nigeria', countryCode: 'NG', region: 'Lagos State', coordinates: { lat: 6.5244, lng: 3.3792 }, population: 15_946_000, wikidataId: 'Q8673', timezone: 'Africa/Lagos', languages: ['en', 'yo'] },
  { slug: 'kairo', name: 'Kairo', nameLocal: 'القاهرة', country: 'Ägypten', countryCode: 'EG', region: 'Kairo', coordinates: { lat: 30.0444, lng: 31.2357 }, population: 10_230_000, wikidataId: 'Q85', timezone: 'Africa/Cairo', languages: ['ar'] },
  { slug: 'kuala-lumpur', name: 'Kuala Lumpur', nameLocal: 'Kuala Lumpur', country: 'Malaysia', countryCode: 'MY', region: 'Federal Territory', coordinates: { lat: 3.1390, lng: 101.6869 }, population: 1_982_000, wikidataId: 'Q1865', timezone: 'Asia/Kuala_Lumpur', languages: ['ms', 'en'] },
  { slug: 'manila', name: 'Manila', nameLocal: 'Maynila', country: 'Philippinen', countryCode: 'PH', region: 'Metro Manila', coordinates: { lat: 14.5995, lng: 120.9842 }, population: 1_846_000, wikidataId: 'Q1461', timezone: 'Asia/Manila', languages: ['tl', 'en'] },
  { slug: 'hanoi', name: 'Hanoi', nameLocal: 'Hà Nội', country: 'Vietnam', countryCode: 'VN', region: 'Hanoi', coordinates: { lat: 21.0285, lng: 105.8542 }, population: 8_054_000, wikidataId: 'Q1858', timezone: 'Asia/Ho_Chi_Minh', languages: ['vi'] },
  { slug: 'marburg', name: 'Marburg', nameLocal: 'Marburg', country: 'Deutschland', countryCode: 'DE', region: 'Hessen', coordinates: { lat: 50.8021, lng: 8.7710 }, population: 76_000, wikidataId: 'Q3869', timezone: 'Europe/Berlin', languages: ['de'] },
  { slug: 'konstanz', name: 'Konstanz', nameLocal: 'Konstanz', country: 'Deutschland', countryCode: 'DE', region: 'Baden-Württemberg', coordinates: { lat: 47.6603, lng: 9.1758 }, population: 85_000, wikidataId: 'Q3126', timezone: 'Europe/Berlin', languages: ['de'] },
];

// ---------------------------------------------------------------------------
// Helper / lookup functions
// ---------------------------------------------------------------------------

const slugIndex = new Map<string, CityData>(
  allCities.map((city) => [city.slug, city]),
);

export function getCityBySlug(slug: string): CityData | undefined {
  return slugIndex.get(slug);
}

export function getCitiesByCountry(countryCode: string): CityData[] {
  return allCities.filter((city) => city.countryCode === countryCode);
}

const DACH_CODES = new Set(['DE', 'AT', 'CH']);

export function getDACHCities(): CityData[] {
  return allCities.filter((city) => DACH_CODES.has(city.countryCode));
}

export function getInternationalCities(): CityData[] {
  return allCities.filter((city) => !DACH_CODES.has(city.countryCode));
}
