/*
  Initiale Coaching-Pakete importieren

  1. Daten-Import
    - 8 verschiedene Coaching-Pakete werden angelegt
    - Einzelsessions (60 Min, 90 Min)
    - Intensiv-Pakete (3 Sessions, 6 Sessions)
    - VIP Experience (VIP Day, Awakening Intensive)
    - Executive & Mastery (Leadership, 12-Monats-Programm)

  2. Details
    - Alle Pakete mit vollständigen Informationen
    - Includes, Benefits, Perfect For als JSONB Arrays
    - Bilder von Pexels
    - Korrekte Gradients und Highlights
*/

INSERT INTO coaching_packages (id, tier, title, subtitle, tagline, duration, price, sessions, format, availability, description, essence, includes, benefits, perfect_for, gradient, image, highlight, is_active, order_index)
VALUES
(
  'einzelsession-60',
  'einzelsession',
  'Einzelsession 60 Min',
  'Intensive 1-zu-1 Begleitung',
  'Dein Durchbruch beginnt jetzt',
  '60 Minuten',
  '€497',
  '1 Session',
  'Video oder Präsenz',
  'Innerhalb 7 Tagen',
  'Eine intensive Einzelsession, in der wir direkt an deinem wichtigsten Thema arbeiten. Persönlich, kraftvoll, transformierend. Absolute Fokussierung auf deine individuelle Situation.',
  'In 60 Minuten kann sich deine Welt verändern – wenn du bereit bist.',
  '["60 Minuten intensive 1-zu-1 Session","Wahlweise Video-Call oder Präsenz","Persönliche Vor- und Nachbereitung","Individuelle Übungsempfehlungen","Audio-Aufzeichnung der Session","14 Tage Follow-up per Email"]'::jsonb,
  '[{"title":"Sofortige Klarheit","description":"Erkenne den Kern deines Themas und den Weg zur Lösung."},{"title":"Tiefe Transformation","description":"Löse blockierende Muster und öffne neue Möglichkeiten."},{"title":"Praktische Integration","description":"Konkrete Werkzeuge für deinen Alltag."}]'::jsonb,
  '["Du hast ein spezifisches Thema oder eine Herausforderung","Du suchst schnelle und tiefgreifende Unterstützung","Du möchtest Anatoly Mook und seine Arbeit kennenlernen","Du brauchst einen kraftvollen Impuls für deine Entwicklung"]'::jsonb,
  'from-sky-500/10 via-cyan-500/5 to-blue-500/5',
  'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  1
),
(
  'einzelsession-90',
  'einzelsession',
  'Einzelsession 90 Min',
  'Tiefenarbeit 1-zu-1',
  'Zeit für echte Tiefe',
  '90 Minuten',
  '€697',
  '1 Session',
  'Video oder Präsenz',
  'Innerhalb 7 Tagen',
  'Mehr Zeit bedeutet mehr Tiefe. In 90 Minuten können wir wirklich in die Essenz deines Themas eintauchen, Zusammenhänge erfassen und nachhaltige Veränderung initiieren.',
  'Echter Wandel braucht Raum – hier bekommt er ihn.',
  '["90 Minuten intensive Tiefenarbeit","Wahlweise Video-Call oder Präsenz","Ausführliche Vor- und Nachbereitung","Individuelle Transformations-Roadmap","Audio-Aufzeichnung der Session","21 Tage Follow-up & Integration Support"]'::jsonb,
  '[{"title":"Tieferes Verständnis","description":"Zeit für komplexe Themen und tiefere Einsichten."},{"title":"Nachhaltige Veränderung","description":"Grundlegende Muster erkennen und transformieren."},{"title":"Ganzheitliche Betrachtung","description":"Zusammenhänge verstehen, das große Bild sehen."}]'::jsonb,
  '["Du möchtest tiefer gehen und grundlegende Muster erkennen","Dein Thema ist komplex und braucht mehr Raum","Du schätzt intensive und gründliche Arbeit","Du willst nachhaltige und tiefgreifende Veränderung"]'::jsonb,
  'from-emerald-500/10 via-teal-500/5 to-cyan-500/5',
  'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  2
),
(
  'intensiv-3',
  'intensiv',
  '3-Session Intensiv-Paket',
  'Fokussierte Transformation',
  'Von der Erkenntnis zur Integration',
  '3 × 90 Minuten',
  '€1.897',
  '3 Sessions',
  'Video oder Präsenz',
  'Start innerhalb 5 Tagen',
  'Ein strukturierter Transformationsprozess über drei intensive Sessions. Von der ersten Erkenntnis über die tiefe Arbeit bis zur Integration in dein Leben. Begleitung, die wirkt.',
  'Transformation ist ein Prozess – gib ihm die Struktur, die er braucht.',
  '["3 × 90 Minuten intensive Sessions","Flexibles Timing (innerhalb 8 Wochen)","Individuelle Session-Vorbereitung","Persönliche Transformations-Roadmap","Alle Aufzeichnungen lebenslang","Zwischen-Sessions Email-Support","30 Tage Integration Support"]'::jsonb,
  '[{"title":"Strukturierter Prozess","description":"Systematische Entwicklung von Erkenntnis zu Integration."},{"title":"Tiefe & Kontinuität","description":"Aufbauende Sessions für nachhaltige Transformation."},{"title":"Begleitung im Alltag","description":"Support zwischen den Sessions für echte Integration."}]'::jsonb,
  '["Du möchtest einen fokussierten Transformationsprozess","Du schätzt Struktur und aufbauende Arbeit","Du bist bereit für tiefgreifende Veränderung","Du möchtest kontinuierliche Begleitung"]'::jsonb,
  'from-amber-500/10 via-orange-500/5 to-yellow-500/5',
  'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  3
),
(
  'intensiv-6',
  'intensiv',
  '6-Session Intensiv-Paket',
  'Umfassende Transformation',
  'Dein Weg zur Meisterschaft',
  '6 × 90 Minuten',
  '€3.497',
  '6 Sessions',
  'Video oder Präsenz',
  'Start innerhalb 5 Tagen',
  'Umfassende Begleitung über einen längeren Zeitraum. Zeit für tiefgreifende Transformation auf allen Ebenen. Von der Auflösung alter Muster bis zur Verkörperung deines höchsten Potenzials.',
  'Meisterschaft entsteht nicht über Nacht – sie entwickelt sich mit Zeit und Hingabe.',
  '["6 × 90 Minuten intensive Sessions","Flexibles Timing (innerhalb 4 Monate)","Ausführliche Transformations-Roadmap","Alle Session-Aufzeichnungen","Durchgehender Email & WhatsApp Support","Bonus: 2 Spontan-Calls (je 30 Min)","60 Tage Integration Support nach Abschluss","Exklusive Meditations-Aufnahmen"]'::jsonb,
  '[{"title":"Umfassende Transformation","description":"Zeit für tiefgreifende Veränderung auf allen Ebenen."},{"title":"Kontinuierliche Begleitung","description":"Durchgehende Unterstützung über mehrere Monate."},{"title":"Nachhaltige Integration","description":"Langfristige Verankerung neuer Muster und Erkenntnisse."}]'::jsonb,
  '["Du möchtest umfassende Transformation erleben","Du schätzt langfristige und tiefe Begleitung","Du bist bereit für fundamentale Veränderung","Du möchtest dein volles Potenzial entfalten"]'::jsonb,
  'from-rose-500/10 via-orange-500/5 to-amber-500/5',
  'https://images.pexels.com/photos/1287145/pexels-photo-1287145.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  4
),
(
  'vip-day',
  'vip',
  'VIP Intensive Day',
  'Ein ganzer Tag nur für dich',
  'Totale Transformation in 24 Stunden',
  '6-8 Stunden',
  '€4.997',
  '1 VIP Tag',
  'Präsenz (exklusive Location)',
  'Nach Vereinbarung',
  'Ein ganzer Tag in exklusiver Atmosphäre, nur du und Anatoly Mook. Intensive Tiefenarbeit ohne Zeitdruck. Luxus-Location, persönliche Betreuung, maximale Transformation.',
  'Wenn ein normaler Tag nicht ausreicht – schaffe einen außergewöhnlichen.',
  '["6-8 Stunden intensive 1-zu-1 Begleitung","Exklusive Premium-Location","Gourmet-Verpflegung während des Tages","Individuelle Session-Struktur nach deinen Bedürfnissen","Alle Aufzeichnungen & Materialien","90 Tage Priority Email & WhatsApp Support","3 Follow-up Calls (je 45 Min)","Persönliche Transformations-Bibel","Bonus: Überraschungs-Geschenk"]'::jsonb,
  '[{"title":"Absolute Exklusivität","description":"Ein ganzer Tag nur für dich und deine Transformation."},{"title":"Maximale Intensität","description":"Ohne Zeitdruck in die tiefsten Schichten eintauchen."},{"title":"Luxus & Komfort","description":"Premium-Umgebung für optimale Transformations-Bedingungen."}]'::jsonb,
  '["Du suchst maximale Transformation in kürzester Zeit","Du schätzt Exklusivität und persönliche Betreuung","Du möchtest intensiv und ohne Ablenkung arbeiten","Du bist bereit für eine tiefgreifende Erfahrung"]'::jsonb,
  'from-amber-500/10 via-yellow-500/5 to-orange-500/5',
  'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  5
),
(
  'executive-leadership',
  'executive',
  'Executive Leadership Coaching',
  'Für bewusste Führungskräfte',
  'Führung aus der tiefen Dimension',
  '3 Monate • 6 Sessions',
  '€9.997',
  '6 × 90 Min + Support',
  'Video & 1× Präsenz',
  'Max. 5 Klienten gleichzeitig',
  'Exklusives Coaching-Programm für Führungskräfte und Unternehmer. Verbinde spirituelle Bewusstheit mit Business-Exzellenz. Führe aus der Stille, handle aus der Kraft, wirke aus dem Sein.',
  'Wahre Führung geschieht nicht durch dich – sie geschieht als du.',
  '["6 × 90 Minuten Executive Sessions","1 VIP Präsenz-Tag (6-8 Std)","Unbegrenzter Priority-Support","24/7 WhatsApp Direct-Line","Business-Cases aus bewusster Perspektive","Individuelle Leadership-Strategie","Alle Aufzeichnungen & Premium-Materialien","Networking mit anderen bewussten Leaders","Lebenslanger Alumni-Status"]'::jsonb,
  '[{"title":"Bewusste Führung","description":"Führe aus Präsenz statt aus Ego, aus Kraft statt aus Kontrolle."},{"title":"Business & Spiritualität","description":"Verbinde geschäftlichen Erfolg mit spiritueller Tiefe."},{"title":"Exklusive Begleitung","description":"Prioritäts-Zugang und intensivste Betreuung."}]'::jsonb,
  '["Du bist Führungskraft oder Unternehmer","Du möchtest Bewusstheit in deine Führung integrieren","Du suchst die Verbindung von Business und Spiritualität","Du bist bereit für Leadership auf höchstem Niveau"]'::jsonb,
  'from-cyan-500/10 via-blue-500/5 to-slate-500/5',
  'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  6
),
(
  'awakening-intensive',
  'vip',
  'Spiritual Awakening Intensive',
  'Retreat-Style Einzelbegleitung',
  'Jenseits von Zeit und Ego',
  '3 Tage Retreat',
  '€12.997',
  '3 Tage intensive Begleitung',
  'Präsenz (Retreat-Location)',
  'Max. 3× pro Jahr',
  'Das intensivste Coaching-Erlebnis. Drei Tage in absoluter Zurückgezogenheit mit Anatoly Mook. Ego-Auflösung, spirituelles Erwachen, höchstes Bewusstsein. Für die, die bereit sind.',
  'Du bist nun reif. Du bist jetzt bereit. Das Erwachen geschieht – jetzt.',
  '["3 Tage intensive 1-zu-1 Retreat-Begleitung","Luxus-Retreat-Location (Alpen oder Toskana)","Vollpension & Premium-Unterkunft","Individuelle Session-Struktur","Meditation, Stille, Natur, Gespräch","6 Monate Follow-up & Integration","Monatliche Check-in Calls","Alle Aufzeichnungen & exklusive Materialien","Lebenslange Alumni-Community","Jährliches Alumni-Retreat Invitation"]'::jsonb,
  '[{"title":"Spirituelles Erwachen","description":"Tiefste Erfahrung von Bewusstsein, Sein, Einheit."},{"title":"Totale Immersion","description":"Drei Tage absolute Fokussierung auf deine Transformation."},{"title":"Lebenslange Verbindung","description":"Alumni-Status und fortlaufende Unterstützung."}]'::jsonb,
  '["Du bist bereit für spirituelles Erwachen","Du suchst die tiefste mögliche Erfahrung","Du möchtest totale Immersion und Zurückgezogenheit","Du bist bereit, alles zu geben"]'::jsonb,
  'from-violet-500/10 via-fuchsia-500/5 to-pink-500/5',
  'https://images.pexels.com/photos/1108572/pexels-photo-1108572.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  7
),
(
  'transformation-12',
  'executive',
  'Transformation Mastery Program',
  'Das ultimative Jahresprogramm',
  'Ein Jahr, das dein Leben für immer verändert',
  '12 Monate',
  '€24.997',
  '24 Sessions + VIP Extras',
  'Hybrid (Video + 4× Präsenz)',
  'Max. 3 Klienten pro Jahr',
  'Das absolute Premium-Programm. Ein ganzes Jahr intensive Begleitung durch Anatoly Mook. Für die, die bereit sind für totale Transformation auf allen Ebenen des Lebens.',
  'Ein Jahr Hingabe. Ein Leben in Freiheit.',
  '["24 × 90 Minuten Sessions (2× monatlich)","4 VIP Präsenz-Tage über das Jahr verteilt","2 × 3-Tage Retreat-Experiences","24/7 Priority WhatsApp Direct-Line","Unbegrenzter Support zwischen Sessions","Individuelle Jahres-Transformations-Roadmap","Monatliche Bonus-Meditationen & Teachings","Zugang zu allen Online-Kursen & Webinaren","Networking mit Elite-Alumni-Circle","Lifelong Alumni-Status & Unterstützung","Jährliches Reunion-Retreat (lebenslang)"]'::jsonb,
  '[{"title":"Totale Transformation","description":"Fundamentale Veränderung auf allen Ebenen deines Lebens."},{"title":"Kontinuierliche Begleitung","description":"Ein ganzes Jahr intensive Unterstützung und Führung."},{"title":"Elite-Zugang","description":"Höchste Priorität und exklusivster Zugang zu Anatoly Mook."}]'::jsonb,
  '["Du bist bereit für die tiefstmögliche Transformation","Du möchtest ein Jahr intensiver Begleitung","Du suchst die absolut höchste Stufe der Arbeit","Du willst dein Leben fundamental und dauerhaft verändern"]'::jsonb,
  'from-amber-500/10 via-rose-500/5 to-purple-500/5',
  'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  8
)
ON CONFLICT (id) DO NOTHING;