/*
  # Initiale Corporate Offers Daten

  Fügt 10 verschiedene Geschäftskunden-Angebote hinzu:
  - 2 Workshops (Halbtag, Ganztag)
  - 2 Training-Serien (Führungskräfte, Team-Entwicklung)
  - 2 Team-Retreats (1 Tag, 3 Tage)
  - 2 Leadership-Programme (3 Monate, 6 Monate)
  - 2 Unternehmens-Transformationen (Team-Transformation, Company-Wide)
*/

INSERT INTO corporate_offers (id, category, title, subtitle, tagline, duration, participants, format, availability, price, description, essence, includes, benefits, ideal_for, program_outline, gradient, image, highlight, is_active, order_index)
VALUES
(
  'team-workshop-halbtag',
  'workshop',
  'Team-Workshop Halbtag',
  'Fokussierte Team-Intervention',
  'Klarheit und Kraft in 4 Stunden',
  '4 Stunden',
  'Bis 15 Personen',
  'Präsenz oder Online',
  'Innerhalb 14 Tagen',
  'Ab €2.497',
  'Ein intensiver Halbtags-Workshop für Teams, die schnell Klarheit schaffen, Blockaden lösen und neue Energie freisetzen möchten. Kompakt, kraftvoll, transformierend.',
  'Transformation braucht nicht immer Tage – manchmal genügen Stunden.',
  '["4 Stunden intensive Team-Intervention","Individuelle Vorbereitung & Bedarfsanalyse","Moderation durch Anatoly Mook","Alle Workshop-Materialien","Foto-Protokoll & Dokumentation","2 Wochen Follow-up Support"]'::jsonb,
  '[{"title":"Schnelle Klarheit","description":"In kurzer Zeit zu konkreten Ergebnissen und Lösungen kommen."},{"title":"Sofortige Wirkung","description":"Blockaden lösen und neue Team-Energie freisetzen."},{"title":"Effizient & kompakt","description":"Perfekt für volle Terminkalender und schnelle Interventionen."}]'::jsonb,
  '["Teams, die schnell Klarheit zu einem spezifischen Thema brauchen","Führungskräfte, die eine fokussierte Team-Intervention wünschen","Unternehmen mit vollen Terminkalendern","Teams in Umbruch- oder Entscheidungssituationen"]'::jsonb,
  '["Ankommen & Einstimmung (30 Min)","Themen-Identifikation & Priorisierung (45 Min)","Tiefenarbeit am Kernthema (120 Min)","Integration & nächste Schritte (45 Min)"]'::jsonb,
  'from-amber-500/10 via-yellow-500/5 to-orange-500/5',
  'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  1
),
(
  'team-workshop-ganztag',
  'workshop',
  'Team-Workshop Ganztag',
  'Intensive Team-Transformation',
  'Ein Tag, der alles verändert',
  '1 Tag (8 Stunden)',
  'Bis 20 Personen',
  'Präsenz oder Online',
  'Innerhalb 21 Tagen',
  'Ab €4.997',
  'Ein ganzer Tag für Ihr Team. Zeit für tiefgreifende Transformation, nachhaltige Lösungen und echte Verbindung. Mit Anatoly Mook als Moderator erleben Sie einen Workshop, der weit über klassische Team-Events hinausgeht.',
  'Wenn ein Team wirklich bereit ist – kann ein Tag eine neue Ära einläuten.',
  '["8 Stunden intensive Team-Arbeit","Ausführliche Vor- & Nachbereitung","Moderation durch Anatoly Mook","Premium Workshop-Location (optional)","Alle Materialien & Dokumentation","Video-Aufzeichnung der Key-Moments","4 Wochen Follow-up & Integration Support"]'::jsonb,
  '[{"title":"Tiefe Transformation","description":"Zeit für grundlegende Muster-Veränderung und nachhaltige Lösungen."},{"title":"Team-Verbindung","description":"Echte Verbindung und Vertrauen im Team aufbauen."},{"title":"Nachhaltige Wirkung","description":"Langfristige Veränderung statt kurzfristiger Impulse."}]'::jsonb,
  '["Teams, die tiefgreifende Transformation anstreben","Führungskräfte, die nachhaltige Team-Entwicklung wünschen","Unternehmen in Veränderungs-Prozessen","Teams, die echte Verbindung und Vertrauen aufbauen möchten"]'::jsonb,
  '["Ankommen & Einstimmung (60 Min)","Team-Diagnose & Muster-Erkennung (90 Min)","Mittagspause (60 Min)","Tiefenarbeit & Transformation (180 Min)","Integration & Commitment (90 Min)"]'::jsonb,
  'from-rose-500/10 via-pink-500/5 to-orange-500/5',
  'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  2
),
(
  'training-series-leadership',
  'training-series',
  'Bewusste Führung Training-Serie',
  '6 Module für moderne Leader',
  'Führung aus der tiefen Dimension',
  '6 × 3 Stunden',
  'Bis 12 Teilnehmer',
  'Hybrid (Online + 1× Präsenz)',
  'Quartalsweise Start',
  'Ab €8.997',
  'Eine 6-teilige Training-Serie für Führungskräfte, die Bewusstheit in ihre Leadership integrieren möchten. Von Selbstführung über Team-Führung bis zu organisationaler Wirkung. Theorie, Praxis, Transformation.',
  'Wahre Führung geschieht nicht durch dich – sie geschieht als du.',
  '["6 × 3 Stunden intensive Training-Module","5 Online-Sessions + 1 Präsenz-Tag","Persönliches Leadership-Assessment","Alle Trainings-Materialien & Workbooks","Zugang zur exklusiven Alumni-Community","Individuelle Coaching-Sessions zwischen Modulen","Zertifikat nach Abschluss"]'::jsonb,
  '[{"title":"Bewusste Führung","description":"Führe aus Präsenz statt aus Ego, aus Klarheit statt aus Kontrolle."},{"title":"Praxis-Integration","description":"Konkrete Tools und Methoden für den Führungsalltag."},{"title":"Peer-Learning","description":"Lernen von und mit anderen bewussten Leadern."}]'::jsonb,
  '["Führungskräfte, die Bewusstheit in ihre Leadership integrieren möchten","Manager, die aus tieferer Dimension führen wollen","Unternehmer, die ihre Führung neu ausrichten möchten","Teams von Führungskräften, die gemeinsam wachsen wollen"]'::jsonb,
  '["Modul 1: Selbstführung & Präsenz","Modul 2: Emotionale Intelligenz","Modul 3: Kommunikation & Dialog","Modul 4: Team-Dynamiken verstehen","Modul 5: Entscheidungen aus Klarheit","Modul 6: Organisationale Wirkung (Präsenz-Tag)"]'::jsonb,
  'from-blue-500/10 via-cyan-500/5 to-teal-500/5',
  'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  3
),
(
  'training-series-team',
  'training-series',
  'Team-Entwicklung Serie',
  '4 Module für High-Performance Teams',
  'Von der Gruppe zum echten Team',
  '4 × 4 Stunden',
  'Bis 15 Teilnehmer',
  'Präsenz oder Online',
  'Monatlicher Start',
  'Ab €6.497',
  'Eine 4-teilige Serie für Teams, die von der Gruppe zum High-Performance Team werden möchten. Vertrauen, Kommunikation, Konflikte, Performance. Alles was ein Team braucht, um großartig zu werden.',
  'Ein echtes Team ist mehr als die Summe seiner Teile.',
  '["4 × 4 Stunden Team-Training","Alle Module mit praktischen Übungen","Team-Assessment vor Start","Alle Materialien & Tools für den Alltag","Zwischen-Sessions Check-ins","4 Wochen Post-Training Support","Team-Zertifikat"]'::jsonb,
  '[{"title":"High-Performance","description":"Grundlagen für exzellente Team-Performance schaffen."},{"title":"Echte Verbindung","description":"Vertrauen und psychologische Sicherheit aufbauen."},{"title":"Konflikt-Kompetenz","description":"Konstruktiv mit Konflikten umgehen und daraus wachsen."}]'::jsonb,
  '["Teams, die High-Performance anstreben","Neu zusammengesetzte Teams","Teams mit Kommunikations- oder Konflikt-Themen","Führungskräfte, die ihr Team entwickeln möchten"]'::jsonb,
  '["Modul 1: Vertrauen & psychologische Sicherheit","Modul 2: Kommunikation & Dialog","Modul 3: Konflikte konstruktiv nutzen","Modul 4: High-Performance & Exzellenz"]'::jsonb,
  'from-emerald-500/10 via-teal-500/5 to-cyan-500/5',
  'https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  4
),
(
  'team-retreat-1day',
  'team-retreat',
  'Team-Retreat Intensiv (1 Tag)',
  'Raus aus dem Alltag, rein in die Transformation',
  'Wenn Teams wirklich Zeit brauchen',
  '1 Tag (inkl. Abend)',
  'Bis 20 Personen',
  'Präsenz (Premium-Location)',
  'Nach Vereinbarung',
  'Ab €7.997',
  'Ein ganzer Tag an einer besonderen Location. Raus aus dem Büro, rein in die Transformation. Mit Workshops, Natur, Reflexion und Team-Zeit. Premium-Verpflegung, professionelle Moderation, nachhaltige Wirkung.',
  'Die besten Team-Durchbrüche passieren nicht im Meeting-Raum.',
  '["Ganztägiges Retreat (9-21 Uhr)","Premium-Location (Natur, Schloss o.ä.)","Moderation durch Anatoly Mook","Gourmet-Vollverpflegung","Workshop-Sessions & Natur-Zeit","Alle Materialien & Dokumentation","Optionale Übernachtung buchbar","8 Wochen Follow-up Support"]'::jsonb,
  '[{"title":"Besondere Atmosphäre","description":"Premium-Locations für optimale Transformations-Bedingungen."},{"title":"Ganzheitliche Erfahrung","description":"Workshop, Natur, Reflexion und Team-Connection."},{"title":"Nachhaltige Wirkung","description":"Intensive Erlebnisse, die lange nachwirken."}]'::jsonb,
  '["Teams, die intensive Transformations-Erfahrung suchen","Führungsteams für strategische Klausuren","Teams nach intensiven Phasen zur Reflexion","Unternehmen, die Team-Kultur stärken möchten"]'::jsonb,
  '["09:00 - Ankommen & Einstimmung","10:00 - Workshop-Session 1","12:30 - Gourmet-Lunch","14:00 - Natur-Zeit & Reflexion","16:00 - Workshop-Session 2","18:30 - Integration & Dinner","20:30 - Lagerfeuer & Ausklang"]'::jsonb,
  'from-violet-500/10 via-purple-500/5 to-fuchsia-500/5',
  'https://images.pexels.com/photos/3184454/pexels-photo-3184454.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  5
),
(
  'team-retreat-3days',
  'team-retreat',
  'Team-Retreat Intensiv (3 Tage)',
  'Tiefgreifende Transformation in der Natur',
  'Drei Tage, die ein Team für immer verändern',
  '3 Tage / 2 Nächte',
  'Bis 16 Personen',
  'Präsenz (Retreat-Center)',
  'Nach Vereinbarung',
  'Ab €19.997',
  'Das ultimative Team-Retreat. Drei Tage intensive Transformation an einem besonderen Ort. Mit Workshops, Coaching, Natur, Stille und tiefer Team-Arbeit. Für Teams, die bereit sind für grundlegende Veränderung.',
  'Wenn ein Team wirklich transformieren will, braucht es Zeit, Raum und Tiefe.',
  '["3 Tage intensive Retreat-Erfahrung","Exklusive Retreat-Location (Alpen, Toskana)","Durchgehende Begleitung durch Anatoly Mook","Luxus-Unterkunft & Vollpension","Workshop-Sessions, Coaching & Natur-Zeit","Alle Materialien & umfassende Dokumentation","Video-Dokumentation der Journey","12 Wochen intensive Follow-up & Integration","Alumni-Community Zugang"]'::jsonb,
  '[{"title":"Tiefste Transformation","description":"Zeit für grundlegende Team-Muster-Veränderung."},{"title":"Retreat-Atmosphäre","description":"Exklusive Locations für optimale Entwicklungs-Bedingungen."},{"title":"Langfristige Wirkung","description":"Nachhaltige Veränderung durch intensive Erfahrung und Follow-up."}]'::jsonb,
  '["Führungsteams für strategische Neuausrichtung","Teams in fundamentalen Transformations-Prozessen","Unternehmen, die Team-Exzellenz anstreben","Teams, die bereit sind für tiefgreifende Veränderung"]'::jsonb,
  '["Tag 1: Ankommen, Einstimmung, Status Quo & Vision","Tag 2: Tiefenarbeit, Muster-Transformation, Team-Dynamiken","Tag 3: Integration, Commitments, nächste Schritte"]'::jsonb,
  'from-pink-500/10 via-rose-500/5 to-orange-500/5',
  'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  6
),
(
  'leadership-program-3months',
  'leadership',
  'Leadership Excellence Program',
  '3-Monats-Programm für Führungskräfte',
  'Von der Position zur Wirkung',
  '3 Monate',
  'Bis 10 Teilnehmer',
  'Hybrid (Online + 2× Präsenz)',
  'Quartalsweise Start',
  'Ab €14.997',
  'Ein 3-monatiges Leadership-Entwicklungs-Programm für Führungskräfte, die ihre Leadership auf das nächste Level bringen möchten. Intensives Training, persönliches Coaching, Peer-Learning und tiefe Transformation.',
  'Exzellente Führung ist keine Position – es ist eine Praxis.',
  '["12 wöchentliche Training-Sessions (á 2,5h)","2 Präsenz-Tage für Tiefenarbeit","6 individuelle 1-zu-1 Coaching-Sessions","Persönliches Leadership-Assessment","Alle Trainings-Materialien & Ressourcen","Zugang zur Leadership-Excellence Community","Monatliche Peer-Learning-Circles","Zertifikat & Alumni-Status"]'::jsonb,
  '[{"title":"Ganzheitliche Entwicklung","description":"Persönlichkeit, Skills und Leadership-Praxis entwickeln."},{"title":"Individuelle Begleitung","description":"Persönliches Coaching zusätzlich zu Gruppen-Training."},{"title":"Peer-Learning","description":"Von und mit anderen exzellenten Leaders lernen."}]'::jsonb,
  '["Führungskräfte, die Leadership-Excellence anstreben","Manager in neuen Führungsrollen","Unternehmer, die ihre Führung professionalisieren","Talents auf dem Weg in Führungsverantwortung"]'::jsonb,
  '["Monat 1: Selbstführung & persönliche Exzellenz","Monat 2: Team-Führung & interpersonelle Wirkung","Monat 3: Organisationale Führung & systemische Wirkung"]'::jsonb,
  'from-cyan-500/10 via-blue-500/5 to-indigo-500/5',
  'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  7
),
(
  'leadership-program-6months',
  'leadership',
  'Leadership Mastery Program',
  '6-Monats-Programm für Senior Leaders',
  'Der Weg zur Leadership Mastery',
  '6 Monate',
  'Bis 8 Teilnehmer',
  'Hybrid (Online + 4× Präsenz)',
  '2× jährlich',
  'Ab €29.997',
  'Das umfassendste Leadership-Programm. Sechs Monate intensive Entwicklung für Senior Leaders, die Mastery in ihrer Führung anstreben. Training, Coaching, Supervision und Peer-Learning auf höchstem Niveau.',
  'Mastery ist keine Destination – es ist ein Weg des lebenslangen Lernens.',
  '["24 wöchentliche Training-Sessions (á 3h)","4 Präsenz-Tage für intensive Tiefenarbeit","12 individuelle 1-zu-1 Coaching-Sessions","Umfassendes Leadership-Assessment (360°)","Alle Premium-Materialien & Ressourcen","Lebenslanger Alumni-Status","Monatliche Mastermind-Circles","Jährliches Alumni-Reunion","Optionale Supervision-Sessions","Persönliches Leadership-Buch am Ende"]'::jsonb,
  '[{"title":"Höchste Entwicklung","description":"Umfassendstes Leadership-Entwicklungs-Programm."},{"title":"Elite-Peer-Gruppe","description":"Lernen und Vernetzen mit anderen Senior Leaders."},{"title":"Lebenslange Community","description":"Alumni-Status und fortlaufende Unterstützung."}]'::jsonb,
  '["Senior Leaders und C-Level Executives","Erfahrene Führungskräfte, die Mastery anstreben","Unternehmer mit Führungsverantwortung","Next-Generation Leaders mit hohem Potenzial"]'::jsonb,
  '["Phase 1 (Monat 1-2): Foundation & Selbstführung","Phase 2 (Monat 3-4): Team & interpersonelle Mastery","Phase 3 (Monat 5-6): Organisation & systemische Wirkung"]'::jsonb,
  'from-slate-500/10 via-gray-500/5 to-zinc-500/5',
  'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  8
),
(
  'transformation-team',
  'transformation',
  'Team-Transformation Journey',
  '6-Monats-Programm für Team-Exzellenz',
  'Von gut zu großartig',
  '6 Monate',
  '1 Team (bis 15 Personen)',
  'Hybrid (Präsenz + Online)',
  'Nach Vereinbarung',
  'Ab €34.997',
  'Ein 6-monatiges Transformations-Programm für Teams, die von gut zu großartig werden möchten. Intensive Begleitung, regelmäßige Interventionen, kontinuierliches Coaching. Für nachhaltige Team-Excellence.',
  'Großartige Teams entstehen nicht zufällig – sie werden entwickelt.',
  '["6 Monate intensive Team-Begleitung","12 Team-Sessions (Präsenz & Online)","Monatliche Führungskräfte-Coachings","Team-Assessment & fortlaufendes Monitoring","Zwischen-Sessions Support & Interventionen","Alle Materialien & Tools","Dokumentation der Team-Journey","3 Monate Post-Programm Support","Team-Excellence Zertifikat"]'::jsonb,
  '[{"title":"Nachhaltige Entwicklung","description":"6 Monate Zeit für tiefgreifende und dauerhafte Veränderung."},{"title":"Kontinuierliche Begleitung","description":"Regelmäßige Touchpoints und fortlaufende Unterstützung."},{"title":"Messbare Ergebnisse","description":"Team-Assessment und klare Performance-Verbesserung."}]'::jsonb,
  '["Teams, die High-Performance anstreben","Führungskräfte, die ihr Team fundamental entwickeln möchten","Unternehmen mit strategischen Team-Entwicklungs-Zielen","Teams in Transformations-Prozessen"]'::jsonb,
  '["Monate 1-2: Foundation & Diagnose","Monate 3-4: Transformation & Entwicklung","Monate 5-6: Integration & Exzellenz"]'::jsonb,
  'from-green-500/10 via-emerald-500/5 to-teal-500/5',
  'https://images.pexels.com/photos/3183153/pexels-photo-3183153.jpeg?auto=compress&cs=tinysrgb&w=1920',
  true,
  true,
  9
),
(
  'transformation-company',
  'transformation',
  'Unternehmens-Transformation',
  'Company-Wide Change & Culture Development',
  'Eine Organisation, ein Bewusstsein',
  '12 Monate',
  'Gesamte Organisation',
  'Maßgeschneidert',
  'Nach Vereinbarung',
  'Auf Anfrage',
  'Das umfassendste Programm für Organisationen, die fundamentale Transformation und Kultur-Entwicklung anstreben. 12 Monate intensive Begleitung auf allen Ebenen. Von der Führung über Teams bis zur gesamten Organisation.',
  'Organisationale Transformation beginnt mit individuellem Bewusstsein.',
  '["12 Monate umfassende Organisations-Begleitung","Leadership-Programm für Führungskräfte","Team-Entwicklung für alle Teams","Change-Management & Kommunikation","Culture-Assessment & -Entwicklung","Monatliche Leadership-Coachings","Quartalsweise All-Hands-Events","Alle Materialien, Tools & Ressourcen","Externe Change-Expertise","12 Monate Post-Programm Support","Langfristige Alumni-Partnerschaft"]'::jsonb,
  '[{"title":"Systemische Transformation","description":"Veränderung auf allen Ebenen der Organisation."},{"title":"Kultur-Entwicklung","description":"Nachhaltige Entwicklung der Unternehmenskultur."},{"title":"Langfristige Partnerschaft","description":"Intensive Begleitung über ein Jahr und darüber hinaus."}]'::jsonb,
  '["Organisationen in fundamentalen Change-Prozessen","Unternehmen, die Kultur-Transformation anstreben","Leadership-Teams mit systemischer Entwicklungs-Vision","Scale-ups und Corporates mit Transformations-Bedarf"]'::jsonb,
  '["Phase 1 (Q1): Assessment & Design","Phase 2 (Q2): Leadership-Entwicklung","Phase 3 (Q3): Team-Transformation","Phase 4 (Q4): Integration & Kultur-Verankerung"]'::jsonb,
  'from-orange-500/10 via-amber-500/5 to-yellow-500/5',
  'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=1920',
  false,
  true,
  10
)
ON CONFLICT (id) DO NOTHING;